Bug/fragment transition toolbar glitch
ZupIT/beagle pull request #1009
Opened 2020-10-07 12:44 UTC by gabrielleonardozup

### Related Issues

Closes #839 
### Description and Example
Create a interface to communicate between BeagleFragment and BeagleActivity to send event when fragment is created, this way we can resend this event in BeagleActivity through onServerDrivenContainerStateChanged callback and avoid user to animate toolbar in wrong states.

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2020-10-07 12:45 UTC, botbeaglezup commented
<!--
  1 Error: The title of PR not follow the...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-10-07 13:28 UTC, uziasferreirazup approved these changes

2020-10-08 12:15 UTC, diogooliveira-zup requested changes

2020-10-08 12:15 UTC, diogooliveira-zup commented on android/beagle/src/main/java/br/com/zup/beagle/android/view/BeagleFragment.kt
> +                .toString() + " must implement OnFragmentCallback")
Hi! It`s seems like a second uncessary conversion .toString()

```suggestion
            throw ClassCastException(context.toString() +" must implement OnFragmentCallback")
```

2020-10-08 13:05 UTC, uziasferreirazup approved these changes

2020-10-08 13:05 UTC, uziasferreirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/view/BeagleFragment.kt
> +                .toString() + " must implement OnFragmentCallback")
```suggestion
            throw ClassCastException("${context.toString()} must implement OnFragmentCallback")
```

2020-10-09 12:10 UTC, uziasferreirazup approved these changes

2020-10-09 12:36 UTC, viniciusguardieirozup approved these changes

2020-10-09 14:01 UTC, merged