fix: parse color when is RGB size
ZupIT/beagle pull request #1033
Opened 2020-10-15 02:26 UTC by matheusribeirozup

Signed-off-by: Matheus Ribeiro <matheus.ribeiro@zup.com.br>

### Related Issues

Closes #1031 

### Description and Example

This PR fixes the error when colors in the RGB format were not parsed in the Beagle.

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2020-10-15 17:07 UTC, viniciusguardieirozup requested changes

2020-10-15 17:07 UTC, viniciusguardieirozup commented on android/beagle/src/test/java/br/com/zup/beagle/android/utils/ColorUtilsTest.kt
> +    fun hexColor_should_return_22FF33_when_2F3_is_given() {
Change to `GIVEN 2F3 WHEN hexCollor is called SHOULD return 22FF33`

2020-10-16 09:45 UTC, uziasferreirazup approved these changes

2020-10-16 12:29 UTC, viniciusguardieirozup approved these changes

2020-10-16 12:41 UTC, merged