fix: adjust context evaluation to return correct types
ZupIT/beagle pull request #1043
Opened 2020-10-17 00:20 UTC by uziasferreirazup

### Related Issues

closes issue #958 

### Description and Example

Adjust to set context always normalize value.
Adjust SendRequest to just normalize value and create an implicit context.
Remove method `trytodeserialize` and adjust the evaluation of the expression to return correct type 

### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2020-10-17 00:21 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: <a href="https://github.com/Zu...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/c9ab35418e22355d1ca7a276ed025a5c41ecb792/android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataEvaluation.kt#L53">android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataEvaluation.kt#L53</a> - Function evaluateBindExpressions has 3 return statements which exceeds the limit of 2.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_android">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-10-17 01:16 UTC, botbeaglezup commented on android/beagle/src/main/java/br/com/zup/beagle/android/components/form/core/FormSubmitter.kt
> +    private fun createUrl(form: FormRemoteAction, formsValue: Map<String, String>) = if (form.method == FormMethodType.GET || form.method == FormMethodType.DELETE)
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/4d8aa400507297e6a523decddba9a85e1ac79cc1/android/beagle/src/main/java/br/com/zup/beagle/android/components/form/core/FormSubmitter.kt#L89"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2020-10-18 16:36 UTC, matheusribeirozup approved these changes

2020-10-19 12:50 UTC, viniciusguardieirozup requested changes

2020-10-19 12:50 UTC, viniciusguardieirozup commented on android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataEvaluationTest.kt
>      fun evaluateContextBindings_with_operation_should_evaluate_contains_operation() {
Please, use the test name defined `GIVEN an operation WHEN evaluateContextBindings called SHOULD evaluate contains operation`

2020-10-19 12:50 UTC, viniciusguardieirozup commented on android/beagle/src/test/java/br/com/zup/beagle/android/context/ContextDataEvaluationTest.kt
>      fun evaluateContextBindings_with_operation_should_throw_error_insert_operation_index_out_of_bound() {
same here

2020-10-19 12:50 UTC, viniciusguardieirozup commented on android/beagle/src/test/java/br/com/zup/beagle/android/utils/ActionExtensionsKtTest.kt
>      fun evaluateExpression_should_evaluate_expression_of_type_boolean() {
same here

2020-10-19 12:50 UTC, viniciusguardieirozup commented on android/beagle/src/test/java/br/com/zup/beagle/android/utils/ActionExtensionsKtTest.kt
>      fun evaluateExpression_should_return_evaluated_value_from_implicit_context_and_normal_context() {
same here

2020-10-19 12:50 UTC, viniciusguardieirozup commented on android/beagle/src/test/java/br/com/zup/beagle/android/utils/ActionExtensionsKtTest.kt
>      fun evaluateExpression_should_return_cached_result_if_there_is() {
same here

2020-10-19 12:53 UTC, viniciusguardieirozup approved these changes

2020-10-20 16:48 UTC, tuliopereirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/context/ContextDataEvaluation.kt
> +        response: Any?): Any? {
break this parentheses to follow Kotlin

2020-10-20 18:30 UTC, merged