feat: adds Container instrumentation tests
ZupIT/beagle pull request #1065
Opened 2020-10-21 14:31 UTC by carlossteinzup

### Related Issues

https://github.com/ZupIT/beagle/issues/500
https://github.com/ZupIT/beagle/issues/1019

### Description and Example

Thi PR adds the instrumentation tests to the container component.

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2020-10-21 14:33 UTC, botbeaglezup commented on backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/controllers/ContainersController.kt
> +import br.com.zup.beagle.automatedtests.builders.*
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/9d4cd0b8e7cd74fa103693bb11a73c089e8f1170/backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/controllers/ContainersController.kt#L19"></span>br.com.zup.beagle.automatedtests.builders.* is a wildcard import. Replace it with fully qualified imports.</td>
    </tr>
  </tbody>
</table>

2020-10-21 14:37 UTC, botbeaglezup commented on iOS/Tests/AutomatedTestsUITests/Steps/ContainerSteps.swift
> +    var application: XCUIApplication!
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/9d4cd0b8e7cd74fa103693bb11a73c089e8f1170/iOS/Tests/AutomatedTestsUITests/Steps/ContainerSteps.swift#L21"></span>Implicitly unwrapped optionals should be avoided when possible.<br />
<code>implicitly_unwrapped_optional</code> <code>ContainerSteps.swift:21</code></td>
    </tr>
  </tbody>
</table>

2020-10-21 14:37 UTC, botbeaglezup commented on iOS/Tests/AutomatedTestsUITests/Steps/ContainerSteps.swift
> +            let texts = [args![0], args![1], args![2]]
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/9d4cd0b8e7cd74fa103693bb11a73c089e8f1170/iOS/Tests/AutomatedTestsUITests/Steps/ContainerSteps.swift#L41"></span>Force unwrapping should be avoided.<br />
<code>force_unwrapping</code> <code>ContainerSteps.swift:41</code></td>
    </tr>
  </tbody>
</table>

2020-10-21 14:37 UTC, botbeaglezup commented on iOS/Tests/AutomatedTestsUITests/Steps/ContainerSteps.swift
> +            let text = args![0]
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/9d4cd0b8e7cd74fa103693bb11a73c089e8f1170/iOS/Tests/AutomatedTestsUITests/Steps/ContainerSteps.swift#L49"></span>Force unwrapping should be avoided.<br />
<code>force_unwrapping</code> <code>ContainerSteps.swift:49</code></td>
    </tr>
  </tbody>
</table>

2020-10-21 14:37 UTC, botbeaglezup commented on iOS/Tests/AutomatedTestsUITests/Steps/ContainerSteps.swift
> +            let texts = [args![0], args![1]]
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/9d4cd0b8e7cd74fa103693bb11a73c089e8f1170/iOS/Tests/AutomatedTestsUITests/Steps/ContainerSteps.swift#L55"></span>Force unwrapping should be avoided.<br />
<code>force_unwrapping</code> <code>ContainerSteps.swift:55</code></td>
    </tr>
  </tbody>
</table>

2020-10-21 14:40 UTC, uziasferreirazup requested changes

2020-10-21 14:40 UTC, uziasferreirazup commented on android/automated-tests/build.gradle
> +}
delete these lines, this has already been added just see the file in full

2020-10-21 14:40 UTC, uziasferreirazup commented on android/automated-tests/src/androidTest/kotlin/br/com/zup/beagle/automatedTests/cucumber/steps/ContainerSteps.kt
> +//
is there any reason why the lines below are commented?
I recommend don't comment code, just don't commit theses lines and create an issue reference about this.

2020-10-21 14:40 UTC, uziasferreirazup commented on android/automated-tests/src/androidTest/kotlin/br/com/zup/beagle/automatedTests/cucumber/steps/Instrumentation.kt
> +//        }
there is some reason to comment these lines?

2020-10-21 14:40 UTC, uziasferreirazup commented on android/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedTests/activity/MainActivity.kt
> +    fun bffUrl() = intent.extras?.getString(BFF_URL_KEY) ?: "http://10.0.2.2:8080/container-test"
always add new test this `bffurl` change I recommend keep the base URL and never commit the change.

2020-10-21 14:40 UTC, uziasferreirazup commented on android/beagle/build.gradle
> +}
delete these lines, this has already been added just see the file in full

2020-10-21 14:40 UTC, uziasferreirazup commented on android/build.gradle
> +    ext.kotlin_version = '1.4.10'
delete these lines, this has already been added just see the file in full

2020-10-21 14:40 UTC, uziasferreirazup commented on android/build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
delete these lines, this has already been added just see the file in full

2020-10-21 14:40 UTC, uziasferreirazup commented on android/preview/build.gradle
> +}
delete these lines, this has already been added just see the file in full

2020-10-21 14:40 UTC, uziasferreirazup commented on android/sample/build.gradle
>  }
delete these lines, this has already been added just see the file in full

2020-10-21 14:45 UTC, botbeaglezup commented on android/automated-tests/build.gradle
> +    implementation "androidx.core:core-ktx:+"
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/07ee3b985dabea1a15252e8d15b996f9fcc6e94b/android/automated-tests/build.gradle#L92"></span>Avoid using + in version numbers; can lead to unpredictable and unrepeatable builds (androidx.core:core-ktx:+)</td>
    </tr>
  </tbody>
</table>

2020-10-21 14:45 UTC, botbeaglezup commented on android/beagle/build.gradle
> +    implementation "androidx.core:core-ktx:+"
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/07ee3b985dabea1a15252e8d15b996f9fcc6e94b/android/beagle/build.gradle#L96"></span>Avoid using + in version numbers; can lead to unpredictable and unrepeatable builds (androidx.core:core-ktx:+)</td>
    </tr>
  </tbody>
</table>

2020-10-21 14:45 UTC, botbeaglezup commented on android/preview/build.gradle
> +    implementation "androidx.core:core-ktx:+"
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/07ee3b985dabea1a15252e8d15b996f9fcc6e94b/android/preview/build.gradle#L61"></span>Avoid using + in version numbers; can lead to unpredictable and unrepeatable builds (androidx.core:core-ktx:+)</td>
    </tr>
  </tbody>
</table>

2020-10-21 14:45 UTC, botbeaglezup commented on android/sample/build.gradle
> +    implementation "androidx.core:core-ktx:+"
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/07ee3b985dabea1a15252e8d15b996f9fcc6e94b/android/sample/build.gradle#L68"></span>Avoid using + in version numbers; can lead to unpredictable and unrepeatable builds (androidx.core:core-ktx:+)</td>
    </tr>
  </tbody>
</table>

2020-10-21 14:47 UTC, carlossteinzup commented on android/automated-tests/src/androidTest/kotlin/br/com/zup/beagle/automatedTests/cucumber/steps/Instrumentation.kt
> +//        }
Yes. The the app was requesting to reeimport the BuildConfig everytime it runs. Then I ask Pó about and he said we could comment that to check later how to fix it. I have removed the lines and will create an issue for it.

2020-10-21 15:24 UTC, carlossteinzup commented on android/automated-tests/build.gradle
> +}
done

2020-10-21 15:24 UTC, carlossteinzup commented on android/automated-tests/src/androidTest/kotlin/br/com/zup/beagle/automatedTests/cucumber/steps/ContainerSteps.kt
> +//
removed
done

2020-10-21 15:25 UTC, carlossteinzup commented on android/automated-tests/src/androidTest/kotlin/br/com/zup/beagle/automatedTests/cucumber/steps/Instrumentation.kt
> +//        }
done

2020-10-21 15:26 UTC, carlossteinzup commented on android/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedTests/activity/MainActivity.kt
> +    fun bffUrl() = intent.extras?.getString(BFF_URL_KEY) ?: "http://10.0.2.2:8080/container-test"
ok. we will set the container test screen as default

2020-10-21 15:26 UTC, carlossteinzup commented on android/beagle/build.gradle
> +}
done

2020-10-21 15:26 UTC, carlossteinzup commented on android/build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
done

2020-10-21 15:26 UTC, carlossteinzup commented on android/preview/build.gradle
> +}
done

2020-10-21 15:26 UTC, carlossteinzup commented on android/sample/build.gradle
>  }
done

2020-10-21 17:14 UTC, uziasferreirazup approved these changes

2020-10-22 12:59 UTC, tiagomnunes89 approved these changes

2020-10-22 13:31 UTC, viniciusguardieirozup approved these changes

2020-10-22 13:31 UTC, viniciusguardieirozup commented on android/preview/build.gradle
> +
please, remove this blank space

2020-10-22 13:35 UTC, caioortu approved these changes

2020-10-22 13:40 UTC, merged