feat: add support to bind in the display to the backend
ZupIT/beagle pull request #1087
Opened 2020-10-26 21:04 UTC by uziasferreirazup

### Related Issues

Closes #1063 

### Description and Example

add support to bind in the display to the backend

### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2020-10-26 21:20 UTC, matheusribeirozup approved these changes

2020-10-26 22:42 UTC, LG95 requested changes
Use the `Bind` sealed class instead of the `BindAttribute` interface.

2020-10-27 12:30 UTC, LG95 approved these changes

2020-10-27 14:13 UTC, matheusribeirozup approved these changes

2020-10-27 14:23 UTC, merged