feat: custom operations
ZupIT/beagle pull request #1096
Opened 2020-10-28 16:08 UTC by gabcoelho

### Related Issues

Closes #1095 

### Description and Example 

Part of Epic #884

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

2020-10-28 16:13 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-10-28 16:20 UTC, botbeaglezup commented on iOS/Sources/Beagle/Sources/ContextExpression/Tests/OperationEvaluation/CustomOperationsTests.swift
> +        dependencies.customOperationsProvider.register(operation: .custom("sum???"), handler: { parameters -> DynamicObject in
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/b2fba7f30eeda153ffe3b19263a01a80c356e3cd/iOS/Sources/Beagle/Sources/ContextExpression/Tests/OperationEvaluation/CustomOperationsTests.swift#L65"></span>Unused parameter “parameters” in a closure should be replaced with _.<br />
<code>unused_closure_parameter</code> <code>CustomOperationsTests.swift:65</code></td>
    </tr>
  </tbody>
</table>

2020-10-29 12:11 UTC, lucasaraujo requested changes

2020-10-29 12:11 UTC, lucasaraujo commented on iOS/Sources/Beagle/Sources/ContextExpression/CustomOperationProvider.swift
> +        }
This guard allows empty name (`""`) and digits only (`"123"`) breaking spec #884 . One possible solution would be match two regex: `#"^\w+$"#` and `#"\D+"#`.
The spec doesn't mention names starting with digits. Should it be allowed?

2020-10-29 12:17 UTC, gabcoelho commented on iOS/Sources/Beagle/Sources/ContextExpression/CustomOperationProvider.swift
> +        }
Nice catch, I forgot about that, I'll make the changes and verify if we will allow names starting with digits. Thanks!!

2020-10-30 19:16 UTC, victorrabelozup reviewed
This solution is good, but I think that the problem of the operation type(native vs custom) is being treated in the wrong place. The parcer should be able to parce correctly for the enum type.  Another solution could be the default operations use the same approach as the custom, using a dictionary instead of a enum, the widgets are done with this idea, using the same functions and dictionary to add both native and custom widgets.

2020-11-03 11:42 UTC, lucasaraujo submitted a review, later dismissed

2020-11-04 13:16 UTC, dantes-git approved these changes

2020-11-04 17:27 UTC, lucasaraujo approved these changes

2020-11-04 17:30 UTC, merged