chore: updated backend modules' dependencies
ZupIT/beagle pull request #1133
Opened 2020-11-10 21:14 UTC by LG95

### Related Issues

None.

### Description and Example

Updated all dependencies of the backend library's modules.

### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2020-11-10 21:24 UTC, ze12augusto requested changes
Check with a project that uses kotlin 1.3. * to see if we have a problem.
Be aware that some features of kotlin 1.4 may not work in 1.3

2020-11-10 21:49 UTC, LG95 commented
@ze12augusto I tested with a simple Micronaut BFF based on the one we suggest in our documentation and against a complex backend module built on top of Beagle, both worked fine. In theory, the libraries Kotlin version isn't known, since even a Java BFF can use the compiled JAR normally.

2020-11-11 13:10 UTC, luismaximozup commented on backend/buildSrc/src/main/kotlin/br/com/zup/beagle/Dependencies.kt
>      object Versions {
Is possible to declare all dependencies version in a build.property or build.gradle as environment variable and retrieve these values so that you only need to update versions in one file?

2020-11-11 13:11 UTC, vitorbassozup commented on backend/automated-tests/build.gradle
> +    id 'org.springframework.boot' version '2.3.5.RELEASE'
Why not use the version in Dependencies.versions? Is it not possible on plugins?

2020-11-11 13:11 UTC, luismaximozup commented on backend/buildSrc/src/main/kotlin/br/com/zup/beagle/Dependencies.kt
> -        const val kotlin = "1.3.72"
Is possible to declare all dependencies version in a build.property or build.gradle as environment variable and retrieve these values so that you only need to update versions in one file?

2020-11-11 13:16 UTC, ze12augusto approved these changes

2020-11-11 13:19 UTC, LG95 commented on backend/automated-tests/build.gradle
> +    id 'org.springframework.boot' version '2.3.5.RELEASE'
We haven't found a way to use the values from dependencies in the plugins declaration.

2020-11-11 13:26 UTC, LG95 commented on backend/buildSrc/src/main/kotlin/br/com/zup/beagle/Dependencies.kt
> -        const val kotlin = "1.3.72"
Other than plugin versions, all our versions are present only in this file.

2020-11-11 13:28 UTC, vitorbassozup approved these changes

2020-11-11 14:48 UTC, merged