refact: create BeagleScope to remove GlobalScope
ZupIT/beagle pull request #1166
Opened 2020-11-23 13:04 UTC by viniciusguardieirozup

### Related Issues

### Description and Example

We have GlobalScope on BeagleSdk, on this PR, I create a BeagleScope to remove this GlobalScope

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

2020-11-23 13:07 UTC, botbeaglezup commented on android/beagle/src/main/java/br/com/zup/beagle/android/utils/BeagleScope.kt
> +import br.com.zup.beagle.android.utils.CoroutineDispatchers
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/bf1c6675d25aad5b186a17823dfcdd9be0388215/android/beagle/src/main/java/br/com/zup/beagle/android/utils/BeagleScope.kt#L19"></span>The import ‘br.com.zup.beagle.android.utils.CoroutineDispatchers’ is unused.</td>
    </tr>
  </tbody>
</table>

2020-11-23 13:09 UTC, botbeaglezup commented
<!--
  1 Error: The title of PR not follow the...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-11-23 13:13 UTC, uziasferreirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/utils/BeagleScope.kt
> +internal class BeagleScope : CoroutineScope{
```suggestion
internal class BeagleScope : CoroutineScope {
```

2020-11-23 19:52 UTC, hthemir submitted a review, later dismissed

2020-11-25 14:42 UTC, uziasferreirazup approved these changes

2020-11-25 14:45 UTC, paulomeurerzup submitted a review, later dismissed

2020-11-25 15:05 UTC, paulomeurerzup commented on android/beagle/src/main/java/br/com/zup/beagle/android/utils/BeagleScope.kt
> +    private val job = Job()
I think we should be using a SupervisorJob instead. Using a SupervisorJob, a failure or cancellation of a child does not cause the supervisor job to fail and does not affect its other children.

Let's say we've started two coroutines in BeagleScope. Without SupervisorJob if one coroutine fails, the other coroutine will be cancelled too.

2020-11-25 15:05 UTC, paulomeurerzup commented on android/beagle/src/main/java/br/com/zup/beagle/android/utils/BeagleScope.kt
> +    override val coroutineContext = job + CoroutineDispatchers.IO
Should we be using CoroutineDispatchers.IO as default? This dispatcher is optimized to disk and network tasks. 

Maybe we should use CoroutineDispatchers.Main as default and let the user change the context of its own coroutines as needed.

2020-11-27 17:59 UTC, paulomeurerzup approved these changes

2020-11-27 18:06 UTC, botbeaglezup commented on android/beagle/src/main/java/br/com/zup/beagle/android/utils/BeagleScope.kt
> +import kotlinx.coroutines.CoroutineDispatcher
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/5a7378ec8de128a915c457a75ddfc8b4d09c265c/android/beagle/src/main/java/br/com/zup/beagle/android/utils/BeagleScope.kt#L19"></span>The import ‘kotlinx.coroutines.CoroutineDispatcher’ is unused.</td>
    </tr>
  </tbody>
</table>

2020-11-30 12:24 UTC, carlossteinzup submitted a review, later dismissed

2020-11-30 16:33 UTC, paulomeurerzup submitted a review, later dismissed

2020-11-30 16:42 UTC, uziasferreirazup requested changes

2020-11-30 16:42 UTC, uziasferreirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/utils/BeagleScope.kt
> +import kotlinx.coroutines.CoroutineDispatcher
Remove the unused import

2020-12-07 13:01 UTC, uziasferreirazup approved these changes

2020-12-07 18:21 UTC, FredericoNoce approved these changes

2020-12-15 13:07 UTC, merged