tests: adds lazy component funtional tests
ZupIT/beagle pull request #1171
Opened 2020-11-24 11:46 UTC by carlossteinzup

### Related Issues

https://github.com/ZupIT/beagle/issues/500
https://github.com/ZupIT/beagle/issues/1016

### Description and Example

Adds functional tests to the Lazy component

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2020-11-24 11:48 UTC, botbeaglezup commented
<!--
  1 Error: The title of PR not follow the...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-11-24 19:50 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-11-25 14:29 UTC, paulomeurerzup commented on backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/LazySuccessScreenBuilder.kt
> +const val MOCKED_CONTAINER = "https://run.mocky.io/v3/b71d4999-0138-467e-bd3e-645540c29b9f"
I know that mocky.io has the option to never expire, but i think that in some point in the future this policy could change and our tests start to failing. Wouldn't it be better to serve this json in our backend service?

2020-11-25 14:38 UTC, uziasferreirazup requested changes

2020-11-25 14:38 UTC, uziasferreirazup commented on backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/LazySuccessScreenBuilder.kt
> +const val MOCKED_CONTAINER = "https://run.mocky.io/v3/b71d4999-0138-467e-bd3e-645540c29b9f"
it is not a good practice to reference a url that everyone does not have access to editing, please put this json in an endpoint locally.

2020-11-25 17:42 UTC, gabcoelho commented on backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/LazySuccessScreenBuilder.kt
> +const val MOCKED_CONTAINER = "https://run.mocky.io/v3/b71d4999-0138-467e-bd3e-645540c29b9f"
done 😁

2020-11-25 17:44 UTC, gabcoelho commented on backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/LazySuccessScreenBuilder.kt
> +const val MOCKED_CONTAINER = "https://run.mocky.io/v3/b71d4999-0138-467e-bd3e-645540c29b9f"
Your right! Changed that, it's way better 😁

2020-11-25 18:16 UTC, carlossteinzup commented on backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/LazySuccessScreenBuilder.kt
> +const val MOCKED_CONTAINER = "https://run.mocky.io/v3/b71d4999-0138-467e-bd3e-645540c29b9f"
We did that but unfortunately it breaks the tests because the endpoint is called before the animation ends and it is not possible to read the previous page.

2020-11-25 18:18 UTC, paulomeurerzup approved these changes

2020-11-25 18:24 UTC, carlossteinzup commented on backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/LazySuccessScreenBuilder.kt
> +const val MOCKED_CONTAINER = "https://run.mocky.io/v3/b71d4999-0138-467e-bd3e-645540c29b9f"
We tried this already but it did not work for this type of tests. The BFF response update the page between the animation and it is not possible to read the previous page.

2020-11-25 20:49 UTC, hthemir submitted a review, later dismissed

2020-11-26 12:59 UTC, paulomeurerzup approved these changes

2020-11-26 13:55 UTC, lucasfonsecazup approved these changes

2020-11-26 14:14 UTC, uziasferreirazup approved these changes

2020-11-27 12:41 UTC, merged

2020-11-27 12:42 UTC, viniciusguardieirozup approved these changes

2020-11-30 10:42 UTC, igorgiumellizup commented on android/automated-tests/src/androidTest/kotlin/br/com/zup/beagle/automatedTests/cucumber/steps/LazyComponentSteps.kt
> +    fun check2ndScreenMessage(text:String) {
I think GenericSteps already has a step to check this. If not, we should put this step there since it is a generic step.