fix/image view remote
ZupIT/beagle pull request #1229
Opened 2020-12-07 21:58 UTC by carlossteinzup

### Related Issues

https://github.com/ZupIT/beagle/issues/1214

### Description and Example

The Image component is not behaving as expected when rendering a Remote image through the ImagePath.Remote attribute on android mobiles. It only seems to work when a defined WIDTH and HEIGHT is set for it.

The example is set on the issue above

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- x] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2020-12-07 22:00 UTC, botbeaglezup commented
<!--
  1 Error: The title of PR not follow the...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-12-07 22:02 UTC, botbeaglezup commented on android/beagle/src/main/java/br/com/zup/beagle/android/cache/imagecomponent/ImageDownloader.kt
> +internal class ImageDownloader() {
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/300c498a4cd5e0e499d0edbc197c3102ca2031e8/android/beagle/src/main/java/br/com/zup/beagle/android/cache/imagecomponent/ImageDownloader.kt#L26"></span>An empty default constructor can be removed.</td>
    </tr>
  </tbody>
</table>

2020-12-07 22:02 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: <a href="https://github.com/Zu...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/300c498a4cd5e0e499d0edbc197c3102ca2031e8/android/beagle/src/main/java/br/com/zup/beagle/android/imagedownloader/DefaultImageDownloader.kt#L21">android/beagle/src/main/java/br/com/zup/beagle/android/imagedownloader/DefaultImageDownloader.kt#L21</a> - The import ‘android.view.View’ is unused.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_android">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-12-07 23:36 UTC, uziasferreirazup commented on android/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedTests/activity/MainActivity.kt
> +    fun bffUrl() = intent.extras?.getString(BFF_URL_KEY) ?: "http://10.0.2.2:8080/image-issue"
return to default url.

2020-12-07 23:38 UTC, uziasferreirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/cache/imagecomponent/ImageDownloader.kt
> -        return beagleBitmapFactory.getBitmap(bitmap, contentWidth, contentHeight)
The `createScaledBitmap` method was used to create a bitmap the size of the image and save it, now you are using exactly what comes from the server, it cannot crash and how is the question of resizing?

2020-12-07 23:42 UTC, uziasferreirazup requested changes
Create a branch to follow the process to generate a hotfix, because this it is a bug in the current version.

2020-12-08 12:51 UTC, carlossteinzup commented on android/beagle/src/main/java/br/com/zup/beagle/android/cache/imagecomponent/ImageDownloader.kt
> -        return beagleBitmapFactory.getBitmap(bitmap, contentWidth, contentHeight)
The resizing will occur, when needed, triggered by the modes selected. When it was being done inside the beagleBitmapFactory, it was preventing the modes to act on it. Now the behaviour is the same as in the local image. It wasnt before.

2020-12-08 14:04 UTC, carlossteinzup commented on android/beagle/src/main/java/br/com/zup/beagle/android/cache/imagecomponent/ImageDownloader.kt
> -        return beagleBitmapFactory.getBitmap(bitmap, contentWidth, contentHeight)
The previous behaviour was preventing the image to render accordingly at the screen. The beagleBitmapFactory was changing the remoteImage aspect ration and was resizing deforming the image, specially when one of the width or height parameters was not informed to build the image view. 

The bitmap is still being created since the BitmapFactory from Android is still being used at the return for this function. I will attempt a solution to the resize question

2020-12-08 19:34 UTC, carlossteinzup commented on android/beagle/src/main/java/br/com/zup/beagle/android/cache/imagecomponent/ImageDownloader.kt
> -        return beagleBitmapFactory.getBitmap(bitmap, contentWidth, contentHeight)
I have checked with iOS and they dont change the bitmap size when receiving images from a remote path.

2020-12-08 19:34 UTC, carlossteinzup commented on android/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedTests/activity/MainActivity.kt
> +    fun bffUrl() = intent.extras?.getString(BFF_URL_KEY) ?: "http://10.0.2.2:8080/image-issue"
chnaged

2020-12-09 15:02 UTC, uziasferreirazup approved these changes

2020-12-09 19:26 UTC, luisoliveirazup approved these changes

2020-12-09 20:58 UTC, merged