test: adds unit tests for the toolbar title generator
ZupIT/beagle pull request #1236
Opened 2020-12-11 12:58 UTC by jenifersantoszup

Signed-off-by: jenifersantoszup <jenifer.santos@zup.com.br>

### Related Issues

Unit tests have been added to ensure that the generateTitle method is called correctly and that the defined title is correct in the toolbar.

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2020-12-11 13:02 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-12-11 13:22 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: <a href="https://github.com/Zu...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/fb9c8dffa193cd3692bda92024b56d5df6b0f71b/android/beagle/src/main/java/br/com/zup/beagle/android/utils/ToolbarManager.kt#L184">android/beagle/src/main/java/br/com/zup/beagle/android/utils/ToolbarManager.kt#L184</a> - Prefer “<code>SHOW_AS_ACTION_IF_ROOM</code>” instead of “<code>SHOW_AS_ACTION_ALWAYS</code>”</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_android">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-12-11 13:35 UTC, carlossteinzup submitted a review, later dismissed

2020-12-15 11:56 UTC, viniciusguardieirozup commented on android/beagle/src/test/java/br/com/zup/beagle/android/utils/ToolbarManagerTest.kt
> +
please, use the new pattern for test, use the @DisplayName to given, when and then

2020-12-15 11:57 UTC, viniciusguardieirozup commented on android/beagle/src/test/java/br/com/zup/beagle/android/utils/ToolbarManagerTest.kt
> +    fun `should be call the configureToolbar method to generate the title`() {
please, use the new pattern for test, use the @DisplayName to given, when and then

2020-12-15 13:21 UTC, uziasferreirazup requested changes

2020-12-15 13:21 UTC, uziasferreirazup commented on android/beagle/build.gradle
> +    testImplementation Dependencies.TestLibraries.mockk
duplicate dependency here, you can remove this line

2020-12-15 13:21 UTC, uziasferreirazup commented on android/beagle/src/test/java/br/com/zup/beagle/android/utils/ToolbarManagerTest.kt
> +@DisplayName("Given a toolbar")
```suggestion
@DisplayName("Given a ToolbarManager")
```

2020-12-15 13:21 UTC, uziasferreirazup commented on android/beagle/src/test/java/br/com/zup/beagle/android/utils/ToolbarManagerTest.kt
> +    fun `verifyCallTheGenerateTitle`() {
```suggestion
    fun verifyCallTheGenerateTitle() {
```

2020-12-15 13:21 UTC, uziasferreirazup commented on android/beagle/src/test/java/br/com/zup/beagle/android/utils/ToolbarManagerTest.kt
>  class ToolbarManagerTest : BaseTest() {
Please follow the guide line of tests:
https://github.com/ZupIT/beagle/wiki/Android-Tests-Style-Guide

2020-12-15 13:21 UTC, uziasferreirazup commented on android/beagle/src/test/java/br/com/zup/beagle/android/utils/ToolbarTextManagerTest.kt
> +class ToolbarTextManagerTest {
Please follow the guideline of tests:
https://github.com/ZupIT/beagle/wiki/Android-Tests-Style-Guide

2020-12-15 13:22 UTC, uziasferreirazup commented
I understand the robolectric test use junit4 but you can use the correct name to write tests `GIVEN ... WHEN... THEN` please read the documentation and adjust the code.

2020-12-15 20:22 UTC, uziasferreirazup approved these changes

2020-12-15 21:10 UTC, carlossteinzup approved these changes

2020-12-15 21:12 UTC, merged