Feature/disabled button
ZupIT/beagle pull request #1273
Opened 2020-12-29 18:42 UTC by FredericoNoce

### Related Issues

https://github.com/ZupIT/beagle/issues/1271

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2020-12-29 18:43 UTC, botbeaglezup commented
<!--
  1 Error: The title of PR not follow the...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-12-29 18:48 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: <a href="https://github.com/Zu...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/2a252e77f9ef6e5471341054dfb5e90f78167f29/backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/ButtonScreenBuilder.kt#L43">backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/ButtonScreenBuilder.kt#L43</a> - The function createButtonScreen is too long (64). The maximum length is 60.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_backend">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-12-29 20:23 UTC, dantes-git submitted a review, later dismissed

2020-12-29 20:31 UTC, gabrielleonardozup approved these changes

2020-12-30 14:27 UTC, matheusribeirozup commented on android/beagle/src/main/java/br/com/zup/beagle/android/components/Button.kt
> +        disabled?.let { bind ->
Shouldn't the button be able to see changes in this property even if it comes with the `disabled` not set?

2020-12-30 14:30 UTC, matheusribeirozup commented on backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/ButtonScreenBuilder.kt
> +                disabled = true
What do you think of using this property from context to reactively enable and disable?
```suggestion
                disabled = expressionOf("@{context.disabled}")
```

2020-12-30 14:49 UTC, carlossteinzup submitted a review, later dismissed

2020-12-30 17:14 UTC, FredericoNoce commented on backend/automated-tests/src/main/kotlin/br/com/zup/beagle/automatedtests/builders/ButtonScreenBuilder.kt
> +                disabled = true
done

2020-12-30 17:32 UTC, carlossteinzup approved these changes

2020-12-30 20:55 UTC, matheusribeirozup approved these changes

2021-01-05 17:18 UTC, uziasferreirazup requested changes

2021-01-05 17:18 UTC, uziasferreirazup commented on android/beagle/src/test/java/br/com/zup/beagle/android/components/ButtonTest.kt
> +    fun should_isEnabled_when_disable_null() {
please follow style guide to write unit test: https://github.com/ZupIT/beagle/wiki/Android-Tests-Style-Guide

2021-01-26 17:22 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-01-26 17:23 UTC, FredericoNoce commented on android/beagle/src/test/java/br/com/zup/beagle/android/components/ButtonTest.kt
> +    fun should_isEnabled_when_disable_null() {
done!

2021-01-26 18:09 UTC, uziasferreirazup approved these changes

2021-01-26 18:31 UTC, matheusribeirozup approved these changes

2021-01-26 18:31 UTC, merged