Feature/action open external url
ZupIT/beagle pull request #1379
Opened 2021-02-22 18:34 UTC by hectorcustodiozup

### Related Issues

#1310 

### Description and Example

New action 'beagle:openExternalUrl' for flutter.

To do so, I added a dependency called 'url_launcher' and created the new action to navigate when 'beagle:openExternalUrl' is called. I also had to upgrade android build gradle from 3.5.0 to 3.5.4 so the navigation could work properly in newer versions of the OS.

### Checklist

Please, check if these important points are met using `[x]`:

- [ ] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [ ] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [ ] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2021-02-22 18:35 UTC, botbeaglezup commented
<!--
  1 Error: The title of PR not follow the...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-02-22 18:39 UTC, botbeaglezup commented
<!--
  0 Errors
  2 Warnings: <a href="https://github.com/Zu...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/e861435a8b307ded613e2b1c1d84602836915d3b/beagle/lib/action/beagle_open_external_url.dart#L18">beagle/lib/action/beagle_open_external_url.dart#L18</a> - Place 'dart:' imports before other imports</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/e861435a8b307ded613e2b1c1d84602836915d3b/beagle/lib/action/beagle_open_external_url.dart#L25">beagle/lib/action/beagle_open_external_url.dart#L25</a> - Only throw instances of classes extending either Exception or Error</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_flutter">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-02-22 22:00 UTC, uziasferreirazup requested changes

2021-02-22 22:00 UTC, uziasferreirazup commented on flutter/beagle/lib/action/beagle_open_external_url.dart
> +      throw 'Could not launch $url';
at beagle we try not to crash the user's application at any time, we just throw a log message to help the developer, so throwing this exception would not be a good practice, what do you think of adding a warning message when there is a problem opening the passed url?
you can use `BeagleInitializer.logger`

2021-02-23 13:16 UTC, hectorcustodiozup commented on flutter/beagle/lib/action/beagle_open_external_url.dart
> +  static Future<void> launchURL(String url) async {
I do not see what kind of test I should create here. As my class simply calls for a library method wich in theory should already be tested in their code. Do I create a simple test only for the call?

2021-02-23 13:39 UTC, uziasferreirazup commented on flutter/beagle/lib/action/beagle_open_external_url.dart
> +  static Future<void> launchURL(String url) async {
yes for good practice unit tests should be done, even if the launch method was tested in another class, you do not have the coverage of that class here, here you can check if the correct call to the `launch` was made with the url that you passed via parameter and also tested if an error occurred the log was called.

2021-02-23 13:43 UTC, uziasferreirazup commented on flutter/beagle/lib/action/beagle_open_external_url.dart
> +      debugPrint('Could not launch $url');
What do you think of using the logger class that we have? it is the official class that we use to log any message to the developer so that he can control whether he will show it or not, this way the external developer cannot do anything.

2021-02-23 13:49 UTC, hectorcustodiozup commented on flutter/beagle/lib/action/beagle_open_external_url.dart
> +      debugPrint('Could not launch $url');
Done!

2021-02-23 18:32 UTC, hectorcustodiozup commented on flutter/beagle/lib/action/beagle_open_external_url.dart
> +  static Future<void> launchURL(String url) async {
I created a unit test for the success case. The 'else' statement when it should check if the logger is called I could not do because I could not instantiate the BeagleInitializer class and after some research on the internet I found out that static classes and methods can not be mocked. I will come back to this problem later.

2021-02-24 12:22 UTC, uziasferreirazup approved these changes

2021-02-24 12:27 UTC, uziasferreirazup approved these changes

2021-02-24 12:27 UTC, uziasferreirazup commented on flutter/beagle/lib/action/beagle_open_external_url.dart
> +  static Future<void> launchURL(String url) async {
I understand.

2021-02-24 19:20 UTC, paulomeurerzup approved these changes

2021-02-24 19:20 UTC, merged