feat: flutter action open native route
ZupIT/beagle pull request #1380
Opened 2021-02-22 18:48 UTC by hectorcustodiozup

### Related Issues

#1310 

### Description and Example
New action beagle:openNativeRoute

Added the missing action for native route navigation. To do so, I created a singleton class to navigate to a previously registered route when the action is called. The main problem I found while working on this issue was the fact that to navigate I needed a `BuildContext` that is required for the flutter `Navigator` class methods. I ended up with a few solutions but most of them required some sort of configuration in the application itself, I finally decided them to use the `BuildContext` that is given when creating a `RemoteView` so I passed its value to my Navigator class and it allowed me to navigate without requiring no further configuration.

### Checklist

Please, check if these important points are met using `[x]`:

- [ ] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [ ] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [ ] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2021-02-22 21:49 UTC, uziasferreirazup requested changes

2021-02-22 21:49 UTC, uziasferreirazup commented on flutter/beagle/lib/action/beagle_open_native_route.dart
> +  BuildContext buildContext;
I believe that having the context saved in a static variable is not a legal way to solve this problem, as you do not guarantee that the rendered view still exists at the time of `pushNamed` and this can generate some memory leak, I recommend doing this in another way, your actions will have a reference to the buildcontext where it was done with this you would be able to call the push view with the correct context

2021-02-22 21:50 UTC, uziasferreirazup commented on flutter/beagle/lib/action/beagle_open_native_route.dart
> +  void navigate(String url) {
What do you think about writing some unit tests for this method?

2021-02-22 21:52 UTC, uziasferreirazup commented on flutter/beagle/lib/action/beagle_open_native_route.dart
> +  BuildContext buildContext;
Example:
```

final Map<String, ActionHandler> defaultActions = {
  'beagle:alert': ({action, view, element}) {
    BeagleAlert.showAlertDialog(
      message: action.getAttributeValue('message'),
      onPressOk: action.getAttributeValue('onPressOk', () {}),
      title: action.getAttributeValue('title', 'Alert'),
    );
  },
// search way to send contex by view executed action
  'beagle:openNativeRoute': ({action, view, element, context}) {
    BeagleNativeNavigator().navigate(context, action.getAttributeValue('route'));
  }
};

class BeagleNativeNavigator {
  factory BeagleNativeNavigator() {
    return _instance;
  }

  BeagleNativeNavigator._constructor();

  static final BeagleNativeNavigator _instance =
      BeagleNativeNavigator._constructor();

  void navigate(BuildContext context, String url) {
    try {
      Navigator.pushNamed(context, url);
    } catch (err) {
      debugPrint('Error: $err while trying to navigate to $url');
    }
  }
}

```

2021-02-23 13:26 UTC, hectorcustodiozup commented on flutter/beagle/lib/action/beagle_open_native_route.dart
> +  BuildContext buildContext;
Do you mean pass the context through the Json payload? And if so, wouldn't that be a break of contract as the other platforms would not use this value in any way?

Nevertheless I am going to try your solution, but If you really mean trhough the json I do not think I can do that.

Another way I found, and it is by far the most recommended among the flutter community is using a globalkey for navigation without context

![image](https://user-images.githubusercontent.com/50678762/108849547-03ee0300-75c1-11eb-8614-a7b7171817f7.png)

It works fine and this was actually the first solution I came up with. But the downside is that the user would have to add the key to their application manually see:

![image](https://user-images.githubusercontent.com/50678762/108849827-60512280-75c1-11eb-9483-959db5e4c4cf.png)
 
What do you think?

2021-02-23 13:47 UTC, uziasferreirazup commented on flutter/beagle/lib/action/beagle_open_native_route.dart
> +  BuildContext buildContext;
that is not what I meant, not necessarily all the data you receive there needs to be in json, because this is a flutter thing and not to save in json, the view that was clicked is a flutter view inside it has a context and it can be sent down and received within the action in the same way as it is done on Android

2021-02-23 13:48 UTC, uziasferreirazup commented on flutter/beagle/lib/action/beagle_open_native_route.dart
> +  BuildContext buildContext;
I also do not recommend referencing by key, because again the components are developed by the developer, I recommend that the moment that there is some interaction on the screen, we pass down which view that had interaction so we could get the current context, without being statically.

2021-02-25 18:18 UTC, hectorcustodiozup commented on flutter/beagle/lib/action/beagle_open_native_route.dart
> +  BuildContext buildContext;
As decided in the metting, we will keep this solution for the moment so I am resolving the conversation. As soon as a way to access the context is found we have to come back to this action and change it accordingly.

2021-02-25 18:56 UTC, matheusribeirozup commented on flutter/beagle/lib/action/beagle_open_native_route.dart
> +  void navigate(String url) {
I agree that there should be at least one test verifying success and another verifying failure of this method.

2021-02-25 20:09 UTC, hectorcustodiozup commented on flutter/beagle/lib/action/beagle_open_native_route.dart
> +  void navigate(String url) {
I added the success case but the failure one I still have to find out how to test static classes to verify if the logger is called or not.

2021-02-25 20:13 UTC, botbeaglezup commented
<!--
  0 Errors
  3 Warnings: <a href="https://github.com/Zu...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/917224cbb3ef56c381367fb0e93219cd877fdd99/beagle/test/action/beagle_open_native_route_test.dart#L1">beagle/test/action/beagle_open_native_route_test.dart#L1</a> - Unused import: 'package:beagle/action/beagle_open_external_url.dart'</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/917224cbb3ef56c381367fb0e93219cd877fdd99/beagle/test/action/beagle_open_native_route_test.dart#L19">beagle/test/action/beagle_open_native_route_test.dart#L19</a> - Prefer final for variable declarations if they are not reassigned</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/917224cbb3ef56c381367fb0e93219cd877fdd99/beagle/test/action/beagle_open_native_route_test.dart#L20">beagle/test/action/beagle_open_native_route_test.dart#L20</a> - Cascade consecutive method invocations on the same reference</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_flutter">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-03-01 16:46 UTC, uziasferreirazup approved these changes

2021-03-01 16:59 UTC, paulomeurerzup approved these changes

2021-03-01 16:59 UTC, merged