cd: dokka reference
ZupIT/beagle pull request #1391
Opened 2021-02-25 18:28 UTC by vitorbassozup

### Description and Example

This PR automatically generates and merges kdocs for backend and android projects and uploads it

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2021-02-25 18:29 UTC, botbeaglezup commented
<!--
  1 Error: The title of PR not follow the...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-02-25 19:15 UTC, luismaximozup approved these changes

2021-02-26 22:19 UTC, LG95 reviewed
You are using some variables without double quotes, which makes your script fragile, breaking if a value becomes something with a space. https://github.com/koalaman/shellcheck/wiki/Sc2086 provides a great explication.

2021-03-01 20:10 UTC, hernandazevedozup commented on fastlane/replace.sh
> +appedTo=""
```suggestion
appendToFile=""
```

2021-03-01 20:12 UTC, hernandazevedozup commented on fastlane/replace.sh
> +        sed -E "s/$match/$replace/g" $file >> $appendTo
```suggestion
    if [[ "$appendToFile" == "" ]]
    then
        sed -i -E "s/$match/$replace/g" $file
    else [[ "$appendToFile" != "" ]]
        sed -E "s/$match/$replace/g" $file >> $appendToFile
```

2021-03-01 20:14 UTC, hernandazevedozup approved these changes
Approved with suggestions

2021-03-01 20:15 UTC, LG95 requested changes

2021-03-01 20:15 UTC, LG95 commented on fastlane/generateDocs.sh
> +source ./replace.sh
Why only separate a single function into another file? Variables can be declared locally inside it.
```suggestion
substitute() {
    match=""
    replace=match
    file=""
    appedTo=""

    while [ $# -gt 0 ]
    do
        if [[ $1 == **"--"** ]]
        then
            param="${1/--/}"
            declare $param="$2"
        fi
        shift
    done

    if [[ "$appendTo" == "" ]]
    then
        sed -i -E "s/$match/$replace/g" $file
    else [[ "$appendTo" != "" ]]
        sed -E "s/$match/$replace/g" $file >> $appendTo
    fi
} 
```

2021-03-02 11:58 UTC, igorgiumellizup commented on fastlane/generateDocs.sh
> +    mkdir -p public
Isn't 'public' too generic of a name? If we are talking about documentation, I suggest we specify more like docs/public or kdocs/public

2021-03-02 12:03 UTC, igorgiumellizup commented on fastlane/generateDocs.sh
> +#!/bin/bash
In order to keep the standards we have inside _fastlane_ folder, I suggest the following for these new scripts:
- place them inside a specify folder, ex fastlane/docs or fastlane/kdocs
- rename them using _ instead of camel case, ex generate_docs

2021-03-02 12:04 UTC, igorgiumellizup commented on fastlane/generateDocs.sh
> +mergeFormatedSearchInfo(){
```suggestion
mergeFormattedSearchInfo(){
```

2021-03-02 12:04 UTC, igorgiumellizup commented on fastlane/generateDocs.sh
> +mergeFormatedDocs(){
```suggestion
mergeFormattedDocs(){
```

2021-03-02 12:04 UTC, igorgiumellizup commented on fastlane/generateDocs.sh
> +copyFormatedDocsToDestination(){
```suggestion
copyFormattedDocsToDestination(){
```

2021-03-02 12:17 UTC, igorgiumellizup commented on fastlane/substitute.sh
> +substitute() {
I can't tell if this script is just replacing files \ chars or also appending contents. How about specifying more names and functions?  I'll write down some suggestions:
- replace_source_for_kdoc.sh
- replace_special_chars.sh
- append_kdoc()
- replace_special_chars()

etc...

2021-03-02 16:57 UTC, vitorbassozup commented on fastlane/replace.sh
> +        sed -E "s/$match/$replace/g" $file >> $appendTo
adopted

2021-03-02 17:05 UTC, vitorbassozup commented on fastlane/generateDocs.sh
> +source ./replace.sh
This function was the one that stood out for me being clearly a candidate for separation as a helper function that's not specific to the doc but just a sed wrapper while the other functions are specific to the specific task of merging the kdocs. I guess I can also separate them between formatting the individual kdocs and merging them.

2021-03-02 17:08 UTC, vitorbassozup commented on fastlane/generateDocs.sh
> +    mkdir -p public
As per your suggestion, I moved everything into a `kdocs` folder. Now when the script generates the public folder with the merged kdocs, it will be inside `kdocs/public`. The reason I chose public was to follow some kind of standard on doc generation (hugo for example chooses public as the default folder name for its generated doc as well)

2021-03-02 17:10 UTC, vitorbassozup commented on fastlane/generateDocs.sh
> +mergeFormatedSearchInfo(){
Nicely caught.

2021-03-02 17:28 UTC, vitorbassozup commented on fastlane/substitute.sh
> +substitute() {
This is mainly a wrapper for the sed command so that is more easily understandable by people not so familiar with it. I first chose substitute as its name because it represents the only sed option it uses (the 's'). Later on, the `appendToFile` argument was introduced as a way to get the resulting substitution and append it to the end of another file.
I can achieve the same results by using something like `inPlace` instead of `appendToFile` that just returns the result of the substitution (in which inPlace corresponds to sed's -i option) and then just use `>>` like so:
* Before: substitute --match something --replace otherthing --file this.txt --appendToFile appendToThisFile.txt
* After: substitute --match something --replace otherthing --file this.txt --inPlace false >> appendToThisFile.txt

What do you think?

2021-03-03 17:14 UTC, LG95 submitted a review, later dismissed

2021-03-03 17:15 UTC, LG95 commented on fastlane/generateDocs.sh
> +source ./replace.sh
The current separation looks a lot better, it was odd to have only a single function separated from the rest of the scipt.

2021-03-10 19:06 UTC, LG95 approved these changes

2021-03-17 18:45 UTC, igorgiumellizup approved these changes

2021-03-25 16:29 UTC, uziasferreirazup approved these changes

2021-03-25 16:30 UTC, merged