feat: Adds BuildContext reference to ActionHandler
ZupIT/beagle pull request #1413
Opened 2021-03-04 17:19 UTC by paulomeurerzup

Signed-off-by: paulomeurerzup <paulo.meurer@zup.com.br>

### Related Issues

Closes#1399

### Description and Example

Adds BuildContext reference to ActionHandler. This was necessary because some operations, such as navigation, depends on that context.

From now on, when a ```BeagleViewJS``` is created, it must be provided a ```ContextProvider```.

The ```ContextProvider ``` is a callback to retrieve the ```BuildContext``` of the Widget where the elements tree of BeagleViewJS are being rendered.

### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2021-03-04 17:39 UTC, botbeaglezup commented
<!--
  0 Errors
  9 Warnings: <a href="https://github.com/Zu...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          9 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/c6de8663699cd0473900e4d9486fdd0c02a891b2/beagle/example/pubspec.yaml#L15">beagle/example/pubspec.yaml#L15</a> - Sort pub dependencies</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/c6de8663699cd0473900e4d9486fdd0c02a891b2/beagle/lib/action/beagle_alert.dart#L34">beagle/lib/action/beagle_alert.dart#L34</a> - 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/c6de8663699cd0473900e4d9486fdd0c02a891b2/beagle/pubspec.yaml#L16">beagle/pubspec.yaml#L16</a> - Sort pub dependencies</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/c6de8663699cd0473900e4d9486fdd0c02a891b2/beagle/pubspec.yaml#L23">beagle/pubspec.yaml#L23</a> - Sort pub dependencies</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/c6de8663699cd0473900e4d9486fdd0c02a891b2/beagle/test/action/beagle_open_native_route_test.dart#L27">beagle/test/action/beagle_open_native_route_test.dart#L27</a> - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/c6de8663699cd0473900e4d9486fdd0c02a891b2/beagle/test/action/beagle_open_native_route_test.dart#L35">beagle/test/action/beagle_open_native_route_test.dart#L35</a> - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/c6de8663699cd0473900e4d9486fdd0c02a891b2/beagle_components/pubspec.yaml#L15">beagle_components/pubspec.yaml#L15</a> - Sort pub dependencies</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/c6de8663699cd0473900e4d9486fdd0c02a891b2/beagle_components/pubspec.yaml#L23">beagle_components/pubspec.yaml#L23</a> - Sort pub dependencies</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/c6de8663699cd0473900e4d9486fdd0c02a891b2/sample/pubspec.yaml#L27">sample/pubspec.yaml#L27</a> - Sort pub dependencies</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_flutter">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-03-05 17:23 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-03-05 19:05 UTC, matheusribeirozup approved these changes

2021-03-08 00:23 UTC, uziasferreirazup requested changes

2021-03-08 00:23 UTC, uziasferreirazup commented on flutter/beagle/lib/beagle_sdk.dart
> +  static Future<void> init({
I believe that leaving the init of the beagle sdk async is not a good approach, as this will cause the user's application to hang waiting for initialization, and we can make this initialize the sync which is much more imperceptible
Example:
```

    ..registerSingletonAsync<BeagleService>(() async {
      final configService = BeagleServiceJS(
        beagleServiceLocator<BeagleJSEngine>(),
        baseUrl: beagleConfig.baseUrl,
        httpClient: httpClient,
        components: components,
        useBeagleHeaders: useBeagleHeaders,
        actions: actions,
        strategy: strategy,
        navigationControllers: navigationControllers,
      );

      await configService.start();
      return configService;
    })
```

and you will have a singleton of beagle service with start called.

2021-03-08 17:01 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: <a href="https://github.com/Zu...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/175313432ab48556d3c9f26b0261367e7edaa877/beagle/lib/beagle_sdk.dart#L34">beagle/lib/beagle_sdk.dart#L34</a> - Unused import: 'package:flutter/widgets.dart'</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_flutter">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-03-08 19:01 UTC, uziasferreirazup approved these changes

2021-03-08 19:15 UTC, matheusribeirozup approved these changes

2021-03-08 19:15 UTC, merged