feat: add new Layout Widgets: Center, Column and Row.
ZupIT/beagle pull request #1432
Opened 2021-03-15 04:19 UTC by uziasferreirazup

### Related Issues

#1414

### Description and Example

The idea is to bring these 3 new components to help developers write a layout in a simpler way.

A new function has been created to facilitate the application of style and others can use it, example:

``` kotlin
fun MyRowStyled(children: List<ServerDrivenComponent>): Container {
    return Styled(Column(
        children = children,
    ), {
        flex.backgroundColor = "#f1f1f1"
    })
}
```

The functions of applying style and flex have also been improved.

before:
``` kotlin
 Button(
            text = textButton,
            styleId = BUTTON_STYLE_ACCESSIBILITY
        ).applyStyle(Style(
            margin = EdgeValue(
                top = 8.unitReal(),
                bottom = 8.unitReal()
            ),
            size = Size(
                height = 40.unitReal()
            ),
            flex = Flex(
                alignItems = AlignItems.CENTER)
        )
```

actual:

``` kotlin
   Button(
            text = textButton,
            styleId = BUTTON_STYLE_ACCESSIBILITY
        ).setStyle {
            margin = EdgeValue(
                top = 8.unitReal(),
                bottom = 8.unitReal()
            )
            size = Size(
                height = 40.unitReal()
            )
            flex.alignItems = AlignItems.CENTER
        }
```

from now on with these new functions you no longer need to instantiate a Flex or Style class, they are instantiated internally.

### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2021-03-15 04:22 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-03-15 04:22 UTC, botbeaglezup commented on backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/ext/FlexExtension.kt
> +class FlexBuilder(private val flexObject: Flex?) {
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/5a130e6b6d40cb8044f3a2ee969422ebf589b64f/backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/ext/FlexExtension.kt#L28"></span>The file name 'FlexExtension' does not match the name of the single top-level declaration 'FlexBuilder'.</td>
    </tr>
  </tbody>
</table>

2021-03-15 04:22 UTC, botbeaglezup commented on backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/ext/StyleExtension.kt
> +fun <T : StyleComponent> Styled(component: T, block: StyleBuilder.() -> Unit): T {
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/5a130e6b6d40cb8044f3a2ee969422ebf589b64f/backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/ext/StyleExtension.kt#L29"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 04:22 UTC, botbeaglezup commented on backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/ext/WidgetExtensions.kt
> +fun <T : Widget> T.accessibility(block: AccessibilityBuilder.() -> Unit) = this.applyAccessibility(AccessibilityBuilder().apply(block).build())
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/5a130e6b6d40cb8044f3a2ee969422ebf589b64f/backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/ext/WidgetExtensions.kt#L87"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2021-03-15 04:22 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Center.kt
> +fun <T : StyleComponent> Center(child: T): T {
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/5a130e6b6d40cb8044f3a2ee969422ebf589b64f/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Center.kt#L25"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 04:22 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Column.kt
> +fun Column(
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/5a130e6b6d40cb8044f3a2ee969422ebf589b64f/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Column.kt#L25"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 04:22 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Row.kt
> +import com.sun.rowset.internal.Row
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/5a130e6b6d40cb8044f3a2ee969422ebf589b64f/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Row.kt#L24"></span>The import 'com.sun.rowset.internal.Row' is unused.</td>
    </tr>
  </tbody>
</table>

2021-03-15 04:22 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Row.kt
> +fun Row(
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/5a130e6b6d40cb8044f3a2ee969422ebf589b64f/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Row.kt#L26"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 04:42 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Expanded.kt
> +fun <T : StyleComponent> Expanded(child: T, grow: Double = 1.0): T {
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/7fa7b5aa65d658ddadc4be676ed2ee0a418577e7/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Expanded.kt#L22"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 04:42 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Margin.kt
> +fun <T : StyleComponent> Margin(child: T, margin: EdgeValue): T {
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/7fa7b5aa65d658ddadc4be676ed2ee0a418577e7/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Margin.kt#L23"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 04:42 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Padding.kt
> +fun <T : StyleComponent> Padding(child: T, padding: EdgeValue): T {
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/7fa7b5aa65d658ddadc4be676ed2ee0a418577e7/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Padding.kt#L23"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 05:11 UTC, botbeaglezup commented on backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt
> +import br.com.zup.beagle.ext.unitReal
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/d8a38d6a98b359c396439feb626f45d901306102/backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt#L19"></span>The import 'br.com.zup.beagle.ext.unitReal' is unused.</td>
    </tr>
  </tbody>
</table>

2021-03-15 05:11 UTC, botbeaglezup commented on backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt
> +import com.sun.org.apache.bcel.internal.generic.VariableLengthInstruction
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/d8a38d6a98b359c396439feb626f45d901306102/backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt#L20"></span>The import 'com.sun.org.apache.bcel.internal.generic.VariableLengthInstruction' is unused.</td>
    </tr>
  </tbody>
</table>

2021-03-15 05:11 UTC, botbeaglezup commented on backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt
> +        fun only(
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/d8a38d6a98b359c396439feb626f45d901306102/backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt#L128"></span>The function only(left: Int?, unitTypeLeft: UnitType, top: Int?, unitTypeTop: UnitType, right: Int?, unitTypeRight: UnitType, bottom: Int?, unitTypeBottom: UnitType) has too many parameters. The current threshold is set to 6.</td>
    </tr>
  </tbody>
</table>

2021-03-15 05:11 UTC, botbeaglezup commented on backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt
> +        fun only(
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/d8a38d6a98b359c396439feb626f45d901306102/backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt#L149"></span>The function only(left: Double?, unitTypeLeft: UnitType, top: Double?, unitTypeTop: UnitType, right: Double?, unitTypeRight: UnitType, bottom: Double?, unitTypeBottom: UnitType) has too many parameters. The current threshold is set to 6.</td>
    </tr>
  </tbody>
</table>

2021-03-15 05:11 UTC, botbeaglezup commented on backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/UnitValue.kt
> +import br.com.zup.beagle.ext.unitReal
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/d8a38d6a98b359c396439feb626f45d901306102/backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/UnitValue.kt#L19"></span>The import 'br.com.zup.beagle.ext.unitReal' is unused.</td>
    </tr>
  </tbody>
</table>

2021-03-15 05:12 UTC, botbeaglezup commented on android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ContextOperationsFragment.kt
>  import br.com.zup.beagle.android.components.layout.NavigationBar
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/d8a38d6a98b359c396439feb626f45d901306102/android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ContextOperationsFragment.kt#L36"></span>The import 'br.com.zup.beagle.android.components.layout.NavigationBar' is unused.</td>
    </tr>
  </tbody>
</table>

2021-03-15 05:12 UTC, botbeaglezup commented on android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ContextOperationsFragment.kt
>  import br.com.zup.beagle.android.components.layout.Screen
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/d8a38d6a98b359c396439feb626f45d901306102/android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ContextOperationsFragment.kt#L37"></span>The import 'br.com.zup.beagle.android.components.layout.Screen' is unused.</td>
    </tr>
  </tbody>
</table>

2021-03-15 05:12 UTC, botbeaglezup commented on android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ContextOperationsFragment.kt
> +fun Column(
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/d8a38d6a98b359c396439feb626f45d901306102/android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ContextOperationsFragment.kt#L53"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 05:12 UTC, botbeaglezup commented on android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ContextOperationsFragment.kt
> +fun <T : StyleComponent> Center(child: T): T {
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/d8a38d6a98b359c396439feb626f45d901306102/android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ContextOperationsFragment.kt#L71"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 05:12 UTC, botbeaglezup commented on android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ContextOperationsFragment.kt
> +fun Row(
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/d8a38d6a98b359c396439feb626f45d901306102/android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ContextOperationsFragment.kt#L79"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 05:12 UTC, botbeaglezup commented on android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ContextOperationsFragment.kt
> +fun <T : StyleComponent> Styled(component: T, block: StyleBuilder.() -> Unit): T {
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/d8a38d6a98b359c396439feb626f45d901306102/android/sample/src/main/java/br/com/zup/beagle/sample/fragment/ContextOperationsFragment.kt#L153"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 05:24 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Expanded.kt
> +fun <T : StyleComponent> Expanded(grow: Double = 1.0, child: T): T {
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/a63707240720f9692c9b8f6d63c2c340982abd0a/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Expanded.kt#L22"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 05:24 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Margin.kt
> +fun <T : StyleComponent> Margin(margin: EdgeValue, child: T): T {
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/a63707240720f9692c9b8f6d63c2c340982abd0a/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Margin.kt#L23"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 05:24 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Padding.kt
> +fun <T : StyleComponent> Padding(padding: EdgeValue, child: T): T {
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/a63707240720f9692c9b8f6d63c2c340982abd0a/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Padding.kt#L23"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 05:24 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/SizedBox.kt
> +fun <T : StyleComponent> SizedBox(width: Int,
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/a63707240720f9692c9b8f6d63c2c340982abd0a/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/SizedBox.kt#L23"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 05:24 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/SizedBox.kt
> +fun <T : StyleComponent> SizedBox(width: Double,
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/a63707240720f9692c9b8f6d63c2c340982abd0a/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/SizedBox.kt#L28"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 05:24 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/SizedBox.kt
> +fun <T : StyleComponent> SizedBox(width: UnitValue,
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/a63707240720f9692c9b8f6d63c2c340982abd0a/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/SizedBox.kt#L33"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 05:33 UTC, botbeaglezup commented on backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt
> +import br.com.zup.beagle.core.StyleComponent
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/febcb107f46483ed52ed9c10fdf715dc77f36d76/backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt#L19"></span>The import 'br.com.zup.beagle.core.StyleComponent' is unused.</td>
    </tr>
  </tbody>
</table>

2021-03-15 05:33 UTC, botbeaglezup commented on backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt
> +import br.com.zup.beagle.ext.unitReal
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/febcb107f46483ed52ed9c10fdf715dc77f36d76/backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt#L20"></span>The import 'br.com.zup.beagle.ext.unitReal' is unused.</td>
    </tr>
  </tbody>
</table>

2021-03-15 05:33 UTC, botbeaglezup commented on backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt
> +import com.sun.org.apache.bcel.internal.generic.VariableLengthInstruction
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/febcb107f46483ed52ed9c10fdf715dc77f36d76/backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt#L21"></span>The import 'com.sun.org.apache.bcel.internal.generic.VariableLengthInstruction' is unused.</td>
    </tr>
  </tbody>
</table>

2021-03-15 05:33 UTC, botbeaglezup commented on backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt
> +    //TODO: discuss with team
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/febcb107f46483ed52ed9c10fdf715dc77f36d76/backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt#L84"></span>This comment contains text that has been defined as forbidden in detekt.</td>
    </tr>
  </tbody>
</table>

2021-03-15 05:33 UTC, botbeaglezup commented on backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt
> +        fun only(
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/febcb107f46483ed52ed9c10fdf715dc77f36d76/backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt#L150"></span>The function only(left: Int?, unitTypeLeft: UnitType, top: Int?, unitTypeTop: UnitType, right: Int?, unitTypeRight: UnitType, bottom: Int?, unitTypeBottom: UnitType) has too many parameters. The current threshold is set to 6.</td>
    </tr>
  </tbody>
</table>

2021-03-15 05:33 UTC, botbeaglezup commented on backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt
> +        fun only(
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/febcb107f46483ed52ed9c10fdf715dc77f36d76/backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/widget/core/Flex.kt#L171"></span>The function only(left: Double?, unitTypeLeft: UnitType, top: Double?, unitTypeTop: UnitType, right: Double?, unitTypeRight: UnitType, bottom: Double?, unitTypeBottom: UnitType) has too many parameters. The current threshold is set to 6.</td>
    </tr>
  </tbody>
</table>

2021-03-15 13:03 UTC, botbeaglezup commented on backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/ext/WidgetExtensions.kt
> +@Deprecated("It was deprecated in version 1.7.0 and will be removed in a future version.",
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/7181f683c5d0a9df0c1a7bad396291a316dc2c38/backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/ext/WidgetExtensions.kt#L86"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2021-03-15 13:03 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Accessibility.kt
> +fun <T : AccessibilityComponent> Accessibility(accessible: Boolean = true,
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/7181f683c5d0a9df0c1a7bad396291a316dc2c38/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/layout/Accessibility.kt#L22"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-15 13:22 UTC, botbeaglezup commented on backend/framework/src/main/kotlin/br/com/zup/beagle/platform/BeaglePlatform.kt
> +fun <T : ServerDrivenComponent> Platform(platform: BeaglePlatform,
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><table>
  <tbody>
    <tr>
      <td><span data-href="https://github.com/ZupIT/beagle/blob/02323722290f3a97f04dce1520673f02f6d9bd9b/backend/framework/src/main/kotlin/br/com/zup/beagle/platform/BeaglePlatform.kt#L21"></span>Function names should match the pattern: ([a-z][a-zA-Z0-9]*)</td>
      <td>(<code>.*</code>)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

2021-03-16 13:53 UTC, hernandazevedozup submitted a review, later dismissed

2021-03-16 16:43 UTC, botbeaglezup commented on backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/ext/FlexExtension.kt
> +/**
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/7197efee602d61d43b5bf102ec9de840b12fadb6/backend/kotlin-core/src/main/kotlin/br/com/zup/beagle/ext/FlexExtension.kt#L55"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2021-03-16 16:43 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/style/Center.kt
> +import br.com.zup.beagle.ext.Styled
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/7197efee602d61d43b5bf102ec9de840b12fadb6/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/style/Center.kt#L21"></span>The import 'br.com.zup.beagle.ext.Styled' is unused.</td>
    </tr>
  </tbody>
</table>

2021-03-16 16:43 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/style/Expanded.kt
> +import br.com.zup.beagle.ext.Styled
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/7197efee602d61d43b5bf102ec9de840b12fadb6/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/style/Expanded.kt#L21"></span>The import 'br.com.zup.beagle.ext.Styled' is unused.</td>
    </tr>
  </tbody>
</table>

2021-03-17 00:58 UTC, matheusribeirozup approved these changes

2021-03-17 04:16 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/style/Expanded.kt
> +import br.com.zup.beagle.ext.Flex
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/c129cd90860f8232cf1c27fc4a886fbe0df2cf3a/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/style/Expanded.kt#L20"></span>The import 'br.com.zup.beagle.ext.Flex' is unused.</td>
    </tr>
  </tbody>
</table>

2021-03-17 18:37 UTC, igorgiumellizup requested changes

2021-03-17 18:37 UTC, igorgiumellizup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/style/Accessibility.kt
> + *  The Accessibility it is a helper to apply accessible in your component
```suggestion
 *  The Accessibility is a helper to apply accessible in your component
```

2021-03-17 18:37 UTC, igorgiumellizup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/style/Accessibility.kt
> + *                      By default is kept as true and it indicates that the view is an accessibility element.
```suggestion
 *                      By default it is kept as true and it indicates that the view is an accessibility element.
```

2021-03-17 18:37 UTC, igorgiumellizup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/style/Center.kt
> + *  The Center it is a helper to apply center options in flex
```suggestion
 *  The Center is a helper to apply center options in flex
```

2021-03-17 18:37 UTC, igorgiumellizup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/style/Expanded.kt
> + *  The Expanded it is a helper to apply grow in your component
```suggestion
 *  The Expanded is a helper to apply grow in your component
```

2021-03-17 18:37 UTC, igorgiumellizup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/style/Margin.kt
> + *  The Margin it is a helper to apply margin in your component
```suggestion
 *  The Margin is a helper to apply margin in your component
```

2021-03-17 18:37 UTC, igorgiumellizup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/style/Padding.kt
> + *  The Padding it is a helper to apply padding in your component
```suggestion
 *  The Padding is a helper to apply padding in your component
```

2021-03-17 18:37 UTC, igorgiumellizup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/style/SizedBox.kt
> + *  The SizedBox it is a helper to apply a size in your component
```suggestion
 *  The SizedBox is a helper to apply a size in your component
```

2021-03-17 18:37 UTC, igorgiumellizup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/style/SizedBox.kt
> + *  The SizedBox it is a helper to apply a size in your component
```suggestion
 *  The SizedBox is a helper to apply a size in your component
```

2021-03-17 18:37 UTC, igorgiumellizup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/style/SizedBox.kt
> + *  The SizedBox it is a helper to apply a size in your component
```suggestion
 *  The SizedBox is a helper to apply a size in your component
```

2021-03-24 01:50 UTC, closed without merging