feat: Android listView multiple templates support
ZupIT/beagle pull request #1590
Opened 2021-05-28 19:23 UTC by paulomeurerzup

### Related Issues

#1523 

### Description and Example

Adds support for multiple templates in ListView.

### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.
- [X] I have made the documentation changes or I created an issue explaining how to document this change on [Docs issues](https://github.com/ZupIT/beagle-docs/issues). Please link the issue here:

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2021-05-28 19:24 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-05-28 19:24 UTC, botbeaglezup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/ListViewTemplate.kt
> +    /**
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/a12282712d408672eedd3f880e70d27b77514af8/backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/ListViewTemplate.kt#L24"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2021-05-28 19:26 UTC, botbeaglezup commented on android/beagle/src/main/java/br/com/zup/beagle/android/components/ListView.kt
> +        return if (children.isNullOrEmpty() && (template != null || templates != null) && dataSource != null) {
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/a12282712d408672eedd3f880e70d27b77514af8/android/beagle/src/main/java/br/com/zup/beagle/android/components/ListView.kt#L198"></span>This condition is too complex (4). Defined complexity threshold for conditions is set to '4'</td>
    </tr>
  </tbody>
</table>

2021-05-28 19:26 UTC, botbeaglezup commented on android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListAdapter.kt
>  internal class ListAdapter(
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/a12282712d408672eedd3f880e70d27b77514af8/android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListAdapter.kt#L35"></span>The constructor(orientation: Int, template: ServerDrivenComponent?, iteratorName: String, key: String?, viewFactory: ViewFactory, listViewModels: ListViewModels, templateList: List<ListViewTemplate>?, originView: View) has too many parameters. The current threshold is set to 7.</ListViewTemplate></td>
    </tr>
  </tbody>
</table>

2021-05-28 19:26 UTC, botbeaglezup commented on android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListAdapter.kt
> +                            if (viewModel.evaluateExpressionForGivenContext(originView, itemContext, it.case) as Boolean) {
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/a12282712d408672eedd3f880e70d27b77514af8/android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListAdapter.kt#L144"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2021-05-28 19:26 UTC, botbeaglezup commented on android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListViewTemplateJson.kt
> +    /**
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/a12282712d408672eedd3f880e70d27b77514af8/android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListViewTemplateJson.kt#L22"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2021-05-28 19:26 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: <a href="https://github.com/Zu...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/a12282712d408672eedd3f880e70d27b77514af8/android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/ScreenContextViewModel.kt#L30">android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/ScreenContextViewModel.kt#L30</a> - Class 'ScreenContextViewModel' with '13' functions detected. Defined threshold inside classes is set to '13'</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_android">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-05-28 19:59 UTC, botbeaglezup commented on android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListAdapter.kt
>  internal class ListAdapter(
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/9373d0a1d8a42b1b7a60081d1e3a942053a69cfa/android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListAdapter.kt#L37"></span>The constructor(orientation: Int, template: ServerDrivenComponent?, iteratorName: String, key: String?, viewFactory: ViewFactory, listViewModels: ListViewModels, templateList: List<ListViewTemplate>?, originView: View) has too many parameters. The current threshold is set to 7.</ListViewTemplate></td>
    </tr>
  </tbody>
</table>

2021-05-28 19:59 UTC, botbeaglezup commented on android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/ScreenContextViewModel.kt
>  internal class ScreenContextViewModel(
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/9373d0a1d8a42b1b7a60081d1e3a942053a69cfa/android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/ScreenContextViewModel.kt#L32"></span>Class 'ScreenContextViewModel' with '13' functions detected. Defined threshold inside classes is set to '13'</td>
    </tr>
  </tbody>
</table>

2021-05-28 20:12 UTC, botbeaglezup commented on android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListAdapter.kt
> +import android.annotation.SuppressLint
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/ad268cc3420cbefea99b5d4665681d150ea8a865/android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListAdapter.kt#L19"></span>The import 'android.annotation.SuppressLint' is unused.</td>
    </tr>
  </tbody>
</table>

2021-05-28 20:12 UTC, botbeaglezup commented on android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/ScreenContextViewModel.kt
> +import android.annotation.SuppressLint
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/ad268cc3420cbefea99b5d4665681d150ea8a865/android/beagle/src/main/java/br/com/zup/beagle/android/view/viewmodel/ScreenContextViewModel.kt#L19"></span>The import 'android.annotation.SuppressLint' is unused.</td>
    </tr>
  </tbody>
</table>

2021-05-31 10:25 UTC, viniciusguardieirozup approved these changes

2021-05-31 12:24 UTC, uziasferreirazup requested changes

2021-05-31 12:24 UTC, uziasferreirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListViewTemplate.kt
> +data class ListViewTemplate (
you’ll need to add annotation `beaglejson` to that object if it won’t crash when the guy turns on the proguard

2021-05-31 12:25 UTC, uziasferreirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListViewTemplate.kt
> +data class ListViewTemplate (
to test if the application will crash just activate the proguard and run the project and open an item with a list

2021-05-31 12:25 UTC, uziasferreirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/components/list/ListViewTemplate.kt
> +data class ListViewTemplate (
just in case all objects that are part of the rendering that goes through the moshi is better to be annotated

2021-05-31 13:51 UTC, uziasferreirazup submitted a review, later dismissed

2021-05-31 19:27 UTC, uziasferreirazup approved these changes

2021-05-31 20:33 UTC, matheusribeirozup approved these changes

2021-05-31 20:33 UTC, merged