feat: add Android pull to refresh component
ZupIT/beagle pull request #1636
Opened 2021-06-17 13:33 UTC by paulomeurerzup

### Related Issues

#1626 

### Description and Example

- Added Android PullToRefresh component
- Added Android local sample
- Added BFF sample

### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.
- [X] I have made the documentation changes or I created an issue explaining how to document this change on [Docs issues](https://github.com/ZupIT/beagle-docs/issues). Please link the issue here:

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2021-06-17 13:34 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-06-17 14:52 UTC, uziasferreirazup requested changes

2021-06-17 14:52 UTC, uziasferreirazup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/PullToRefresh.kt
> +    @get:JsonProperty("isRefreshing") val isRefreshing: Bind<Boolean>? = null,
there is some reason to add annotation `get:JsonProperty` ?

2021-06-17 14:52 UTC, uziasferreirazup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/PullToRefresh.kt
> +data class PullToRefresh(
I know it's a pojo object but it would be interesting to add equal serialization and deserialization test has on android.

2021-06-17 14:55 UTC, viniciusguardieirozup approved these changes

2021-06-17 17:33 UTC, paulomeurerzup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/PullToRefresh.kt
> +    @get:JsonProperty("isRefreshing") val isRefreshing: Bind<Boolean>? = null,
jackson has a problem in kotlin when serializing properties starting with "is" that are not Boolean.

https://github.com/FasterXML/jackson-module-kotlin/issues/80

2021-06-17 18:52 UTC, matheusribeirozup commented on android/beagle/src/main/java/br/com/zup/beagle/android/components/refresh/PullToRefresh.kt
> +        context: ContextData?,
This constructor must have a value default for the context, otherwise the user will be forced to pass one, even if it is null.
```suggestion
        context: ContextData? = null,
```

2021-06-17 18:54 UTC, matheusribeirozup commented on android/beagle/src/main/java/br/com/zup/beagle/android/components/refresh/PullToRefresh.kt
> +        isRefreshing: Bind<Boolean>? = null,
What do you think to receive a boolean here?
```suggestion
        isRefreshing: Boolean? = null,
```

2021-06-17 18:55 UTC, matheusribeirozup commented on android/beagle/src/test/java/br/com/zup/beagle/android/components/refresh/PullToRefreshTest.kt
> +            verify(exactly = once()) { swipeRefreshLayout.setOnRefreshListener(any()) }
```suggestion
            verify(exactly = 1) { swipeRefreshLayout.setOnRefreshListener(any()) }
```

2021-06-17 18:57 UTC, matheusribeirozup commented on android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/serializerDataFactory.kt
> +"""
What do you think about doing another test with a json without expressions?

2021-06-17 19:00 UTC, matheusribeirozup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/PullToRefresh.kt
> +        context: ContextData?,
```suggestion
        context: ContextData? = null,
```

2021-06-17 19:01 UTC, matheusribeirozup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/PullToRefresh.kt
> +        isRefreshing: Bind<Boolean>? = null,
```suggestion
        isRefreshing: Boolean? = null,
```

2021-06-17 19:01 UTC, matheusribeirozup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/ui/PullToRefresh.kt
> +        isRefreshing = isRefreshing,
```suggestion
        isRefreshing = valueOfNullable(isRefreshing),
```

2021-06-17 19:02 UTC, paulomeurerzup commented on android/beagle/src/main/java/br/com/zup/beagle/android/components/refresh/PullToRefresh.kt
> +        isRefreshing: Bind<Boolean>? = null,
It must be an expression. isRefreshing can updated dynamically.

2021-06-21 17:52 UTC, botbeaglezup commented
<!--
  1 Error: Tests have failed, see below f...
  0 Warnings
  0 Messages
  1 Markdown
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | Classname | Time|
--- | --- | ---|
GIVEN a preview Activity WHEN on close called THEN should show correct toast message | br.com.zup.beagle.android.preview.PreviewActivityTest | 0.233|


<p align="right" data-meta="generated_by_android">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-06-22 19:45 UTC, matheusribeirozup approved these changes

2021-06-23 13:30 UTC, uziasferreirazup approved these changes

2021-06-23 13:58 UTC, merged