feat: flutter with yoga beta
ZupIT/beagle pull request #1680
Opened 2021-07-01 03:19 UTC by matheusribeirozup

### Description and Example

This PR adds the `yoga_engine` library and provides the first ever integration across the community with Flutter + Yoga + SD!  
😎🚀🙌

Key changes:
- Only the `Container` component has been fully integrated to Yoga.
- Some changes were made to `PageView`, `PageIndicator` and `Image`.
- The `Image` component has been integrated to Yoga as well, but there is a known issue where the width and height must be provided to Yoga be able to render it.

Some considerations:
- Nested Scrolls are quite problematic with Flutter and specially with Yoga.
- Scroll always need a height, otherwise it will interfere with Yoga calculations.

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.
- [ ] I have made the documentation changes or I created an issue explaining how to document this change on [Docs issues](https://github.com/ZupIT/beagle-docs/issues). Please link the issue here:

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2021-07-01 03:20 UTC, botbeaglezup commented
<!--
  0 Errors
  2 Warnings: PR is classed as Work in Progr...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-07-01 03:21 UTC, botbeaglezup commented on backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/ScrollViewScreenBuilder.kt
>  import br.com.zup.beagle.core.Style
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/55ee09d925999d2c98cf88770cf37932dba1a4da/backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/ScrollViewScreenBuilder.kt#L19"></span>The import 'br.com.zup.beagle.core.Style' is unused.</td>
    </tr>
  </tbody>
</table>

2021-07-01 03:21 UTC, botbeaglezup commented on backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/ScrollViewScreenBuilder.kt
>  import br.com.zup.beagle.ext.applyStyle
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/55ee09d925999d2c98cf88770cf37932dba1a4da/backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/ScrollViewScreenBuilder.kt#L20"></span>The import 'br.com.zup.beagle.ext.applyStyle' is unused.</td>
    </tr>
  </tbody>
</table>

2021-07-01 03:21 UTC, botbeaglezup commented on backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/ScrollViewScreenBuilder.kt
>  import br.com.zup.beagle.ext.unitPercent
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/55ee09d925999d2c98cf88770cf37932dba1a4da/backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/ScrollViewScreenBuilder.kt#L22"></span>The import 'br.com.zup.beagle.ext.unitPercent' is unused.</td>
    </tr>
  </tbody>
</table>

2021-07-01 03:21 UTC, botbeaglezup commented on backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/ScrollViewScreenBuilder.kt
>  import br.com.zup.beagle.ext.unitReal
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/55ee09d925999d2c98cf88770cf37932dba1a4da/backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/ScrollViewScreenBuilder.kt#L23"></span>The import 'br.com.zup.beagle.ext.unitReal' is unused.</td>
    </tr>
  </tbody>
</table>

2021-07-01 03:23 UTC, botbeaglezup commented
<!--
  1 Error: Could not run lint without set...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Could not run lint without setting report path or report file doesn't exists</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_flutter">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-07-01 13:10 UTC, uziasferreirazup requested changes

2021-07-01 13:10 UTC, uziasferreirazup commented on flutter/beagle/android/build.gradle
> +    buildToolsVersion '30.0.3'
Are these lines necessary?
then we need to raise this point if we are going to warn the user that he will need to have ndk installed on android

2021-07-01 13:10 UTC, uziasferreirazup commented on flutter/beagle_components/lib/beagle_tab_bar.dart
> +    size: BeagleSize(
why do we need to use beagle size?

2021-07-01 13:10 UTC, uziasferreirazup commented on flutter/beagle_components/lib/beagle_image.dart
> +class BeagleImage extends StatefulWidget with YogaWidget {
Hadn't it been combined to just change the container at first and the other components leave the yoga unmodified?

2021-07-01 13:10 UTC, uziasferreirazup commented on flutter/beagle/lib/style/style_builder.dart
> +/*
for the user to be able to use his container, this class must be on beagle.dart to be viewed in his app

2021-07-01 13:25 UTC, matheusribeirozup commented on flutter/beagle_components/lib/beagle_tab_bar.dart
> +    size: BeagleSize(
I just changed the class name from `Size` to `BeagleSize` to avoid name conflicts.

2021-07-01 13:34 UTC, matheusribeirozup commented on flutter/beagle_components/lib/beagle_image.dart
> +class BeagleImage extends StatefulWidget with YogaWidget {
I made this change to remove the limitation from previous `Image` implementation. This component, at this moment, also has a size necessity to be render.

2021-07-01 13:59 UTC, matheusribeirozup commented on flutter/beagle/android/build.gradle
> +    buildToolsVersion '30.0.3'
Its not necessary, but I strongly recommend we apply this, because there are some improvements on ndk performance. And the buildTools default version, are quite old.

2021-07-01 14:22 UTC, matheusribeirozup commented on flutter/beagle/lib/style/style_builder.dart
> +/*
As discussed, every code must be placed inside the `/src` directory, so this will be created later.

2021-07-02 14:20 UTC, uziasferreirazup approved these changes

2021-07-02 17:16 UTC, dantes-git submitted a review, later dismissed

2021-07-03 14:10 UTC, Tiagoperes commented on flutter/sample/android/app/build.gradle
> +    buildToolsVersion '30.0.3'
Why did you need this? Is it necessary? Should we add it to our documentation?

2021-07-03 14:12 UTC, Tiagoperes submitted a review, later dismissed

2021-07-03 15:28 UTC, matheusribeirozup commented on flutter/sample/android/app/build.gradle
> +    buildToolsVersion '30.0.3'
Flutter is no longer using default versions, so these version specifications have been removed.

2021-07-03 19:14 UTC, uziasferreirazup approved these changes

2021-07-04 12:40 UTC, Tiagoperes approved these changes

2021-07-04 12:40 UTC, merged