feat: flutter alpha preparation
ZupIT/beagle pull request #1684
Opened 2021-07-05 23:03 UTC by matheusribeirozup

### Description and Example

This PR prepare Beagle Flutter to be released on alpha stage:
- Points to `yoga_engine` published version at the Beagle's `pubspec.yalm` file.
- Creates a `readme.md` file with all information needed by any first beagle user.

This is still WIP because the documentation must be released first, given that are references to it in the `readme.md` file.

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.
- [x] I have made the documentation changes or I created an issue explaining how to document this change on [Docs issues](https://github.com/ZupIT/beagle-docs/issues). Please link the issue here:

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2021-07-05 23:05 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: PR is classed as Work in Progr...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-07-06 13:03 UTC, igorgiumellizup requested changes

2021-07-06 13:03 UTC, igorgiumellizup commented on flutter/readme.md
> +
I think the description above, of Custom components, actions and operations are redundant. It could be omitted

2021-07-06 13:03 UTC, igorgiumellizup commented on flutter/readme.md
> +- [Global context](todo): learn how to manipulate the global context in Beagle Flutter.
```suggestion
- [Global context](todo): allows manipulation of the global context in Beagle Flutter.
```

2021-07-06 13:03 UTC, igorgiumellizup commented on flutter/readme.md
> +- [Analytics](todo): observe every action executed and navigation performed.
```suggestion
- [Analytics](todo): gives information of every action executed, such as navigation data.
```

2021-07-06 13:03 UTC, igorgiumellizup commented on flutter/readme.md
> +We're currently in alpha. We'll move to beta as soon as we have every layout tool (Yoga) working as expected. Here's
```suggestion
Currently in alpha. It'll be moved to beta as soon as we have every layout tool (Yoga) working as expected. Here's
```

2021-07-06 13:39 UTC, matheusribeirozup commented on flutter/readme.md
> +method. This params tells everything Beagle needs to know to render your widgets. Here we show only the basic options
In case I'm referring to the method's parameters, then it's in the plural.

2021-07-06 13:58 UTC, matheusribeirozup commented on flutter/readme.md
> +
I think it's positive to let explicit what the user can customize.

2021-07-06 19:16 UTC, igorgiumellizup submitted a review, later dismissed

2021-07-06 19:40 UTC, igorgiumellizup approved these changes

2021-07-06 21:21 UTC, uziasferreirazup approved these changes

2021-07-06 21:21 UTC, merged