Feat/android/multi module kapt
ZupIT/beagle pull request #1690
Opened 2021-07-13 20:09 UTC by paulomeurerzup

### Related Issues

Closes #1436 

### Description and Example

This PR aims to change Beagle's Android annotation processor. Now, it will be possible to register Beagle components in application secondary modules and dependencies.

#### How it gonna work?

From now on, every module or dependency that uses Beagle's annotation processor will generate a group of classes called **_Registrar_**. This classes will keep track of all Beagle components registered inside a specific module.

When generating the `BeagleSetup` class for a module, Beagle'a annotation processor will look for **_Registrar_** classes inside a previously known package named **_br.com.zup.beagle.android.registrar_** on the processing environment.

Beagle's annotation processor will then join the currently processing module registered components with the components found on _**Registrar**_ classes of dependencies.

##### Meet Registrar classes

**_Registrar_** classes will be always generated inside a known package named: `br.com.zup.beagle.android.registrar`. This is necessary, because kapt will look for **_Registrar_** classes inside this package on dependency tree every time it process module annotations.

Due the fact that every module will generate **_Registrar_** classes in a package with the same name across the project, **_Registrar_** classes names must have a dynamic suffix. This suffix can be automatically generated, or can be configured using kapt argument in build.gradle file:

```
kapt {
    arguments {
        arg("beagle.moduleName", "sample")
    }
}
```

This configuration will generate **_Registrar_** classes names like: _RegisteredActionsRegistrarSample_.

For sake of readability, is always recommended the use of `beagle.moduleName` argument. If this argument isn’t present, kapt will generate a random UUID suffix for Registrar classes.

Dynamic generated classes names will look like: _RegisteredActionsRegistrar59c20e58331c4f11b84d377475593739_

Generated classes:

**PropertiesRegistrar**: Keeps track of all BeagleSetup properties registered inside the module.

**RegisteredActionsRegistrar**: Keeps track of all actions registered inside the module.

**RegisteredControllerRegistrar**: Keeps track of all controllers registered inside the module.

**RegisteredCustomTypeAdaptersRegistrar**: Keeps track of all type adapters registered inside the module.

**RegisteredCustomValidatorRegistrar**: Keeps track of all validators registered inside the module.

**RegisteredOperationsRegistrar**: Keeps track of all operations registered inside the module.

**RegisteredWidgetsRegistrar**: Keeps track of all widgets registered inside the module.

##### BeagleSetup and BeagleConfig issue

Before this change, every module that used Beagle's annotation processor generated the `BeagleSetup` class. This is a problem when you want to create a module that, for instance, will have only widgets.

The problem is that `BeagleConfig` is a non null property inside `BeagleSetup` class so, we’ve ended up having to register a dummy `BeagleConfig` class inside that module.

To solve this situation, now it’s possible to disable `BeagleSetup` class generation in modules where it’s not needed. This is done by adding the following kapt argument to the beagle.gradle:

```
kapt {
    arguments {
        arg("beagle.generateSetupClasses", "false")
    }
}
```

##### Properties that are unique

Some properties are unique inside BeagleSetup class. This means that can only register one component of that type on your entire project structure. Properties that are unique includes:

- DesignSystem;
- HttpClient;
- BeagleConfig;
- …

If you register a component that should be unique twice on your project structure, Beagle’s annotation processor will complain and doesn’t compile your project.

Beagle’s annotation processor was changed to always show the complete path to components that were defined multiple times in the error message. It will sound like:

> error: BeagleConfig defined multiple times: 
> public final class AppBeagleConfig implements br.com.zup.beagle.android.setup.BeagleConfig {
>              ^
>   br.com.zup.beagle.sample.AppBeagleConfig
>   br.com.zup.beagle.android.modulea.ModuleABeagleConfig
>   
>   You must remove one implementation from the application.

#### TL;DR

Now it’s possible to register Beagle components in a multi-module project. You can have a module where you gonna register your Widgets, other module where you’ll do network configuration and so on.

Every module that will register some Beagle component must define Beagle annotation processor in the build.gradle file e.g.

`kapt "br.com.zup.beagle:android-processor:1.0.0"`

You can specify if a specific module needs to generate BeagleSetup class using beagle.generateSetupClasses kapt argument and you can specify Registrar classes name suffix (for sake of readability) using beagle.moduleName kapt argument e.g.

```
kapt {
    arguments {
        arg("beagle.moduleName", "sample")
        arg("beagle.generateSetupClasses", "false")
    }
}
```

### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.
- [X] I have made the documentation changes or I created an issue explaining how to document this change on [Docs issues](https://github.com/ZupIT/beagle-docs/issues). Please link the issue here:

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2021-07-13 20:09 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-07-13 20:15 UTC, botbeaglezup commented on android/processor-shared-code/src/main/kotlin/br/com/zup/beagle/compiler/shared/BeagleProcessorUtils.kt
> +fun forEachRegisteredDependency(
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/515094e1cfd1c111ab635b3927e2deecba4af364/android/processor-shared-code/src/main/kotlin/br/com/zup/beagle/compiler/shared/BeagleProcessorUtils.kt#L26"></span>Function forEachRegisteredDependency is nested too deeply.</td>
    </tr>
  </tbody>
</table>

2021-07-13 20:15 UTC, botbeaglezup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleSetupProcessor.kt
> +        PropertiesRegistrarProcessor().process(processingEnv, properties, "$PROPERTIES_REGISTRAR_CLASS_NAME${getModuleName()}")
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/515094e1cfd1c111ab635b3927e2deecba4af364/android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleSetupProcessor.kt#L254"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2021-07-13 20:15 UTC, botbeaglezup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleSetupPropertyGenerator.kt
> +                var typeElement = processingEnv.elementUtils.getTypeElement(registeredDependency.second.removeSuffix("()"))
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/515094e1cfd1c111ab635b3927e2deecba4af364/android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleSetupPropertyGenerator.kt#L51"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2021-07-13 20:15 UTC, botbeaglezup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleSetupPropertyGenerator.kt
> +                    typeElement = processingEnv.elementUtils.getTypeElement(registeredDependency.second.substringBefore("::"))
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/515094e1cfd1c111ab635b3927e2deecba4af364/android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleSetupPropertyGenerator.kt#L53"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2021-07-13 20:15 UTC, botbeaglezup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/PropertiesRegistrarProcessor.kt
> +                registeredProperties.append("\tPair(\"${propertySpec.name}\", \"\"\"${propertySpec.initializer.toString()}\"\"\"),\n")
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/515094e1cfd1c111ab635b3927e2deecba4af364/android/processor/src/main/java/br/com/zup/beagle/android/compiler/PropertiesRegistrarProcessor.kt#L91"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2021-07-13 20:15 UTC, botbeaglezup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/generatefunction/GenerateFunctionComponentRegistrar.kt
> +        return "\n\tPair(\"\"\"${buildElementKey(element, annotation)}\"\"\",\"${getPackageName(element)}.${element.simpleName}\"),"
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/515094e1cfd1c111ab635b3927e2deecba4af364/android/processor/src/main/java/br/com/zup/beagle/android/compiler/generatefunction/GenerateFunctionComponentRegistrar.kt#L56"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2021-07-13 20:15 UTC, botbeaglezup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/generatefunction/GenerateFunctionCustomAdapter.kt
> +        return "${registeredDependency.first} -> ${registeredDependency.second}() as $BEAGLE_TYPE_ADAPTER_INTERFACE$BREAK_LINE"
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/515094e1cfd1c111ab635b3927e2deecba4af364/android/processor/src/main/java/br/com/zup/beagle/android/compiler/generatefunction/GenerateFunctionCustomAdapter.kt#L174"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2021-07-13 20:15 UTC, botbeaglezup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/generatefunction/RegisterControllerProcessor.kt
> +                registeredWidgets.append("\n    \"${registeredDependency.first}\" -> ${registeredDependency.second}$CONTROLLER_DEFINITION_SUFFIX")
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/515094e1cfd1c111ab635b3927e2deecba4af364/android/processor/src/main/java/br/com/zup/beagle/android/compiler/generatefunction/RegisterControllerProcessor.kt#L170"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2021-07-13 20:15 UTC, botbeaglezup commented on backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/AnnotationTestBuilder.kt
> +import br.com.zup.beagle.analytics.ScreenEvent
<table data-meta="generated_by_backend">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/515094e1cfd1c111ab635b3927e2deecba4af364/backend/sample/core/src/main/kotlin/br/com/zup/beagle/sample/builder/AnnotationTestBuilder.kt#L19"></span>The import 'br.com.zup.beagle.analytics.ScreenEvent' is unused.</td>
    </tr>
  </tbody>
</table>

2021-07-20 14:12 UTC, botbeaglezup commented on android/processor-shared-code/src/main/kotlin/br/com/zup/beagle/compiler/shared/RegistrarComponentsProvider.kt
> +abstract class RegistrarComponentsProvider {
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/f599efc6e42891267ef2ce0495e97d4082f58082/android/processor-shared-code/src/main/kotlin/br/com/zup/beagle/compiler/shared/RegistrarComponentsProvider.kt#L24"></span>An abstract class without a concrete member can be refactored to an interface.</td>
    </tr>
  </tbody>
</table>

2021-07-22 14:18 UTC, igorgiumellizup commented on android/processor-shared-code/src/main/kotlin/br/com/zup/beagle/compiler/shared/RegistrarComponentsProvider.kt
> +interface RegistrarComponentsProvider {
RegisterComponentsProvider*

2021-07-22 14:19 UTC, igorgiumellizup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleProcessorUtils.kt
> +fun beagleClassesGenerationDisabled(processingEnv: ProcessingEnvironment): Boolean {
It's not clear what this method does. Try adding a verb to its name, following method naming conventions

2021-07-22 14:20 UTC, igorgiumellizup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleSetupProcessor.kt
> +    private val actionRegistrarFactoryProcessor = GenericFactoryProcessor(
register*

2021-07-22 14:21 UTC, igorgiumellizup requested changes
ok

2021-07-22 14:27 UTC, igorgiumellizup commented
agora q vi q ta em draft, sorry heheeh

2021-07-23 21:04 UTC, uziasferreirazup approved these changes

2021-07-26 13:18 UTC, matheusribeirozup approved these changes

2021-07-26 13:24 UTC, merged