fix: moshi type converter generic
ZupIT/beagle pull request #870
Opened 2020-09-03 15:31 UTC by diogooliveira-zup

### Related Issues

#715 

### Description and Example

This fix makes Beagle able to register custom adapters do help moshi serialize/deserialize non POJO data

### Checklist

Please, check if these important points are met using `[x]`:

- [ ] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [ ] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [ ] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2020-09-03 15:48 UTC, tuliopereirazup requested changes

2020-09-03 15:48 UTC, tuliopereirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/generic/TypeAdapterResolverImpl.kt
> +internal class TypeAdapterResolverImpl: TypeAdapterResolver {
This class should be generated.

2020-09-03 15:48 UTC, tuliopereirazup commented on android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt
>  }
Create one test for other kind of object adapter.

2020-09-03 15:48 UTC, tuliopereirazup commented on android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/serializerDataFactory.kt
> +fun makeArrayList() = """
Does this function is used?

2020-09-03 15:48 UTC, tuliopereirazup commented on android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt
> +        val array = arrayListOf(firstElement)
Same here.

2020-09-03 15:48 UTC, tuliopereirazup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleAnnotationProcessor.kt
> +            RegisterBeagleAdapter::class.java.canonicalName
You registered the Interface but not created any logic to it.

2020-09-03 15:53 UTC, tuliopereirazup requested changes

2020-09-03 15:53 UTC, tuliopereirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/generic/BeagleGenericAdapterFactory.kt
> +        val genericAdapter = TypeAdapterResolverImpl().getAdapter<Type>(type)
Inject this class on constructor instead of instantiating it every time `create` is called.

2020-09-03 15:54 UTC, tuliopereirazup requested changes

2020-09-03 17:08 UTC, diogooliveira-zup commented on android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/serializerDataFactory.kt
> +fun makeArrayList() = """
Done!

2020-09-03 17:11 UTC, diogooliveira-zup commented on android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/generic/BeagleGenericAdapterFactory.kt
> +        val genericAdapter = TypeAdapterResolverImpl().getAdapter<Type>(type)
Done!

2020-09-03 17:13 UTC, diogooliveira-zup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleAnnotationProcessor.kt
> +            RegisterBeagleAdapter::class.java.canonicalName
Yeah will be in the next part of commit

2020-09-05 14:31 UTC, botbeaglezup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleSetupProcessor.kt
> +        registerBeagleAdapterProcessor.process("br.com.zup.beagle.android.data.serializer.adapter.generic", roundEnvironment)
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/a5c77d81589d7289a0083f8e54bdb7f25c9217a6/android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleSetupProcessor.kt#L95"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2020-09-05 14:31 UTC, botbeaglezup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/RegisterBeagleAdapterProcessor.kt
> +import com.squareup.kotlinpoet.*
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/a5c77d81589d7289a0083f8e54bdb7f25c9217a6/android/processor/src/main/java/br/com/zup/beagle/android/compiler/RegisterBeagleAdapterProcessor.kt#L23"></span>com.squareup.kotlinpoet.* is a wildcard import. Replace it with fully qualified imports.</td>
    </tr>
  </tbody>
</table>

2020-09-05 14:31 UTC, botbeaglezup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/RegisterBeagleAdapterProcessor.kt
> +            val elementParameterizedTypeName = ((typeElement.interfaces[0] as DeclaredType).elementType as DeclaredType).asElement()
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/a5c77d81589d7289a0083f8e54bdb7f25c9217a6/android/processor/src/main/java/br/com/zup/beagle/android/compiler/RegisterBeagleAdapterProcessor.kt#L106"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2020-09-05 14:31 UTC, botbeaglezup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/RegisterBeagleAdapterProcessor.kt
> +                    adapters.append("$elementParameterizedTypeName$JAVA_CLASS -> $element() as $BEAGLE_TYPE_ADAPTER_INTERFACE\n")
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/a5c77d81589d7289a0083f8e54bdb7f25c9217a6/android/processor/src/main/java/br/com/zup/beagle/android/compiler/RegisterBeagleAdapterProcessor.kt#L110"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2020-09-05 14:31 UTC, botbeaglezup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/RegisterBeagleAdapterProcessor.kt
> +    private fun createParameterizedType(adapters: StringBuilder, item: DeclaredType, element: TypeElement? = null): StringBuilder {
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/a5c77d81589d7289a0083f8e54bdb7f25c9217a6/android/processor/src/main/java/br/com/zup/beagle/android/compiler/RegisterBeagleAdapterProcessor.kt#L126"></span>Line detected that is longer than the defined maximum line length in the code style.</td>
    </tr>
  </tbody>
</table>

2020-09-05 14:33 UTC, diogooliveira-zup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleAnnotationProcessor.kt
> +            RegisterBeagleAdapter::class.java.canonicalName
Done!

2020-09-05 14:51 UTC, diogooliveira-zup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleSetupProcessor.kt
> +        registerBeagleAdapterProcessor.process("br.com.zup.beagle.android.data.serializer.adapter.generic", roundEnvironment)
Done!

2020-09-05 14:51 UTC, diogooliveira-zup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleSetupProcessor.kt
> +        registerBeagleAdapterProcessor.process("br.com.zup.beagle.android.data.serializer.adapter.generic", roundEnvironment)
Done!

2020-09-05 14:51 UTC, diogooliveira-zup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/RegisterBeagleAdapterProcessor.kt
> +import com.squareup.kotlinpoet.*
Done!

2020-09-05 14:51 UTC, diogooliveira-zup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/RegisterBeagleAdapterProcessor.kt
> +            val elementParameterizedTypeName = ((typeElement.interfaces[0] as DeclaredType).elementType as DeclaredType).asElement()
Done!

2020-09-05 14:51 UTC, diogooliveira-zup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/RegisterBeagleAdapterProcessor.kt
> +                    adapters.append("$elementParameterizedTypeName$JAVA_CLASS -> $element() as $BEAGLE_TYPE_ADAPTER_INTERFACE\n")
Done!

2020-09-05 14:51 UTC, diogooliveira-zup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/RegisterBeagleAdapterProcessor.kt
> +    private fun createParameterizedType(adapters: StringBuilder, item: DeclaredType, element: TypeElement? = null): StringBuilder {
Done!

2020-09-05 15:03 UTC, diogooliveira-zup commented on android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt
>  }
Testes remove after moshi problem to provide default in JSON

2020-09-05 15:03 UTC, diogooliveira-zup commented on android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt
> +        val array = arrayListOf(firstElement)
Testes remove after moshi problem to provide default in JSON

2020-09-05 15:04 UTC, diogooliveira-zup commented on android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt
> +        val jsonComponent = listOf(firstElement).toString()
Test removed after moshi problem to provide default in JSON

2020-09-08 18:17 UTC, botbeaglezup commented on android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleSetupProcessor.kt
>      fun process(
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/d57ca5ffbfb568ecd7e4f5e6f783aa4fa7009d3c/android/processor/src/main/java/br/com/zup/beagle/android/compiler/BeagleSetupProcessor.kt#L56"></span>The function process is too long (64). The maximum length is 60.</td>
    </tr>
  </tbody>
</table>

2020-09-08 18:48 UTC, botbeaglezup commented
<!--
  1 Error: Tests have failed, see below f...
  0 Warnings
  0 Messages
  7 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | Classname | Time|
--- | --- | ---|
getMoshiDataFormatted_evaluate_JSONObject_with_string | br.com.zup.beagle.android.utils.BeagleMoshiExtensionsTest | 0.395|
getMoshiDataFormatted_evaluate_JSONArray_with_int | br.com.zup.beagle.android.utils.BeagleMoshiExtensionsTest | 0.029|
getMoshiDataFormatted_evaluate_int | br.com.zup.beagle.android.utils.BeagleMoshiExtensionsTest | 0.012|
getMoshiDataFormatted_evaluate_double | br.com.zup.beagle.android.utils.BeagleMoshiExtensionsTest | 0.02|
getMoshiDataFormatted_evaluate_JSONObject_with_int | br.com.zup.beagle.android.utils.BeagleMoshiExtensionsTest | 0.015|
getMoshiDataFormatted_evaluate_json_with_double | br.com.zup.beagle.android.utils.BeagleMoshiExtensionsTest | 0.01|
getMoshiDataFormatted_evaluate_JSONArray_with_double | br.com.zup.beagle.android.utils.BeagleMoshiExtensionsTest | 0.008|


### Tests: 

Name | Classname | Time|
--- | --- | ---|
evaluateExpression_should_evaluate_expression_of_type_int | br.com.zup.beagle.android.utils.ActionExtensionsKtTest | 0.487|
evaluateExpression_should_evaluate_expression_of_type_double | br.com.zup.beagle.android.utils.ActionExtensionsKtTest | 0.558|
evaluateExpression_should_evaluate_expression_of_type_boolean | br.com.zup.beagle.android.utils.ActionExtensionsKtTest | 0.522|
evaluateExpression_should_return_JSONArray_evaluated_with_multiple_expressions | br.com.zup.beagle.android.utils.ActionExtensionsKtTest | 0.556|
evaluateExpression_should_evaluate_JSONObject | br.com.zup.beagle.android.utils.ActionExtensionsKtTest | 0.521|
evaluateExpression_should_return_JSONArray_evaluated | br.com.zup.beagle.android.utils.ActionExtensionsKtTest | 0.48|
evaluateExpression_should_return_JSONObject_evaluated | br.com.zup.beagle.android.utils.ActionExtensionsKtTest | 0.52|
evaluateExpression_should_return_JSONObject_evaluated_with_multiple_expressions | br.com.zup.beagle.android.utils.ActionExtensionsKtTest | 0.508|
evaluateExpression_should_evaluate_JSONArray | br.com.zup.beagle.android.utils.ActionExtensionsKtTest | 0.475|


### Tests: 

Name | Classname | Time|
--- | --- | ---|
evaluateContextBindings_should_get_value_from_context_and_deserialize_JSONArray | br.com.zup.beagle.android.context.ContextDataEvaluationTest | 0.768|
evaluateContextBindings_should_get_value_from_context_and_deserialize_JSONObject | br.com.zup.beagle.android.context.ContextDataEvaluationTest | 0.623|


### Tests: 

Name | Classname | Time|
--- | --- | ---|
make_should_return_moshi_to_deserialize_a_FormValidation | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.221|
make_should_return_moshi_to_deserialize_a_PageView | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.064|
make_should_create_contextData_with_double | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.036|
make_should_create_contextData_with_primitive | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.023|
make_should_return_moshi_to_deserialize_a_CustomAndroidAction | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.025|
make_should_return_moshi_to_serialize_a_UndefinedAction | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.062|
make_should_create_contextData_with_integer | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.021|
moshi_should_deserialize_internalObject_using_component_type_attribute | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.05|
make_should_return_moshi_to_deserialize_a_ListView | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.046|
make_should_return_moshi_to_deserialize_a_FormLocalAction | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.025|
make_should_return_moshi_to_deserialize_a_TabView | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.04|
make_should_return_moshi_to_deserialize_a_Container | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.054|
moshi_should_serialize_contextData_with_double | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.01|
make_should_create_contextData_with_jsonArray | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.01|
moshi_should_convert_and_revert_contextData_with_integer | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.013|
make_should_return_moshi_to_deserialize_a_PageIndicator | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.048|
make_should_return_moshi_to_deserialize_a_ConfirmAction | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.039|
moshi_should_deserialize_bindComponent | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.053|
make_should_return_moshi_to_deserialize_a_ScreenWidget | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.064|
moshi_should_serialize_contextData_with_integer | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.025|
make_should_return_moshi_to_deserialize_a_Image_Local | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.067|
make_should_return_moshi_to_deserialize_a_LazyComponent | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.04|
make_should_return_moshi_to_deserialize_a_AlertAction | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.026|
moshi_should_convert_and_revert_contextData_with_double | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.017|
make_should_create_contextData_with_jsonObject | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.01|
make_should_return_moshi_to_deserialize_a_FormInput | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.042|
make_should_return_moshi_to_deserialize_a_ScrollView | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.038|
make_should_return_moshi_to_deserialize_a_NetworkImage | br.com.zup.beagle.android.data.serializer.BeagleMoshiTest | 0.042|


### Tests: 

Name | Classname | Time|
--- | --- | ---|
Data sent should be an JSON object | br.com.zup.beagle.android.action.SendRequestTest | 1.068|


### Tests: 

Name | Classname | Time|
--- | --- | ---|
executeActions_should_parse_object_value_to_JSONObject | br.com.zup.beagle.android.context.ContextActionExecutorTest | 0.807|
executeActions_should_parse_list_of_object_value_to_JSONArray | br.com.zup.beagle.android.context.ContextActionExecutorTest | 0.776|


### Tests: 

Name | Classname | Time|
--- | --- | ---|
normalize_should_return_new_contextData_when_value_type_is_list | br.com.zup.beagle.android.context.ContextDataExtensionsKtTest | 0.339|
normalize_should_return_new_contextData_when_value_type_is_object | br.com.zup.beagle.android.context.ContextDataExtensionsKtTest | 0.344|


<p align="right" data-meta="generated_by_android">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-09-10 04:03 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-09-10 12:07 UTC, matheusribeirozup approved these changes

2020-09-10 17:51 UTC, closed without merging