feat: add expression support in remote route navigation
ZupIT/beagle pull request #890
Opened 2020-09-09 19:10 UTC by jenifersantoszup

### Related Issues

Closes #860  

### Description and Example

Bind support has been added to the remote navigation route

### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.

2020-09-09 19:11 UTC, botbeaglezup commented on android/sample/src/main/java/br/com/zup/beagle/sample/fragment/NavigationFragment.kt
> +import br.com.zup.beagle.widget.core.*
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/1c32f72be2e72df3b5e50f655ca6825c76931324/android/sample/src/main/java/br/com/zup/beagle/sample/fragment/NavigationFragment.kt#L37"></span>br.com.zup.beagle.widget.core.* is a wildcard import. Replace it with fully qualified imports.</td>
    </tr>
  </tbody>
</table>

2020-09-09 19:11 UTC, botbeaglezup commented on android/sample/src/main/java/br/com/zup/beagle/sample/fragment/TabViewFragment.kt
> +import br.com.zup.beagle.android.components.*
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/1c32f72be2e72df3b5e50f655ca6825c76931324/android/sample/src/main/java/br/com/zup/beagle/sample/fragment/TabViewFragment.kt#L26"></span>br.com.zup.beagle.android.components.* is a wildcard import. Replace it with fully qualified imports.</td>
    </tr>
  </tbody>
</table>

2020-09-09 19:11 UTC, botbeaglezup commented on android/sample/src/main/java/br/com/zup/beagle/sample/fragment/TabViewFragment.kt
> +import br.com.zup.beagle.widget.core.*
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/1c32f72be2e72df3b5e50f655ca6825c76931324/android/sample/src/main/java/br/com/zup/beagle/sample/fragment/TabViewFragment.kt#L35"></span>br.com.zup.beagle.widget.core.* is a wildcard import. Replace it with fully qualified imports.</td>
    </tr>
  </tbody>
</table>

2020-09-09 19:11 UTC, botbeaglezup commented on android/sample/src/main/java/br/com/zup/beagle/sample/fragment/TabViewFragment.kt
>      override fun onCreateView(
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/1c32f72be2e72df3b5e50f655ca6825c76931324/android/sample/src/main/java/br/com/zup/beagle/sample/fragment/TabViewFragment.kt#L38"></span>The function onCreateView is too long (64). The maximum length is 60.</td>
    </tr>
  </tbody>
</table>

2020-09-09 19:52 UTC, botbeaglezup commented on android/sample/src/main/java/br/com/zup/beagle/sample/fragment/TabViewFragment.kt
>      override fun onCreateView(
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/8c9b79653c5a7cd5c95db42213d9bb2b3cdb1369/android/sample/src/main/java/br/com/zup/beagle/sample/fragment/TabViewFragment.kt#L49"></span>The function onCreateView is too long (64). The maximum length is 60.</td>
    </tr>
  </tbody>
</table>

2020-09-10 05:42 UTC, uziasferreirazup submitted a review, later dismissed

2020-09-10 05:42 UTC, uziasferreirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/data/PreFetchHelper.kt
> +            if (route.url is Bind.Expression) return
What do you think about adding some warnings to help the developer?
Search in the project the class called `BeagleMessageLogs`  add this method.
```
   fun expressionNotSupportInPreFetch() {
        BeagleLoggerProxy.warning("expression is not support in pre fetch")
    }
```
and call this function in 
```suggestion
            if (route.url is Bind.Expression) {
            BeagleMessageLogsexpressionNotSupportInPreFetch()
            return
            }
```

2020-09-10 05:42 UTC, uziasferreirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/RouteAdapterFactory.kt
> +                BeagleMoshi.moshi.adapter(Boolean::class.java).toJson(writer, value.shouldPrefetch)
I think you don't need to use `BeagleMoshi.moshi` you can use only `moshi`
```suggestion
moshi.adapter(Boolean::class.java).toJson(writer, value.shouldPrefetch)
```

2020-09-10 05:42 UTC, uziasferreirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/RouteAdapterFactory.kt
> +                BeagleMoshi.moshi.adapter(Screen::class.java).toJson(writer, value.fallback)
the same comment above

2020-09-10 05:42 UTC, uziasferreirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/RouteAdapterFactory.kt
> +                BeagleMoshi.moshi.adapter(Screen::class.java).toJson(writer, value.screen)
the same comment above

2020-09-10 14:20 UTC, gabrielleonardozup commented on android/beagle/src/main/java/br/com/zup/beagle/android/action/Navigate.kt
> +    }
A Suggestion here is, for being a function from Route class, we should consider put this code in other file to not mix logic of Route and Navigate.

2020-09-10 14:22 UTC, gabrielleonardozup commented on android/beagle/src/main/java/br/com/zup/beagle/android/action/Navigate.kt
> +    }
Maybe here is a better place for function mentioned above.

2020-09-10 14:26 UTC, gabrielleonardozup commented on android/beagle/src/main/java/br/com/zup/beagle/android/data/PreFetchHelper.kt
> +                BeagleMessageLogs.expressionNotSupportInPreFetch()
We can send an expression in Url field? Is there no exclusive field for expression values?

2020-09-10 14:30 UTC, gabrielleonardozup commented on android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/RouteAdapterFactory.kt
> +            Route.Remote(url, value["shouldPrefetch"] as Boolean, convertScreen(value["fallback"]))
A better pattern here is create constants for this strings ( "url", "fallback" ... ) so this way we avoid accidental refactoring in this strings and we gain reusability.

2020-09-10 14:38 UTC, gabrielleonardozup commented on android/beagle/src/test/java/br/com/zup/beagle/android/action/NavigateTest.kt
> +        verify(exactly = once()) { BeagleNavigator.pushView(rootView.getContext(), route.copy(url = Bind.Value("test"))) }
Other suggestion here: If you want to verify exactly a pushView call from BeagleNavigator object with these exactly two arguments you should consider not mock pushView behavior with any() and any(), it may cause a false positive situation.
 If it is the behavior you want, mock exactly as you want.

2020-09-10 14:43 UTC, gabrielleonardozup commented on android/sample/src/main/java/br/com/zup/beagle/sample/fragment/TabViewFragment.kt
> +                                        )
Other suggestion :D : Extract this child container creation to a separated method to avoid this error ( maximum function length) and improve readability.

2020-09-10 19:46 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-09-10 19:47 UTC, botbeaglezup commented on android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/RouteAdapterFactory.kt
> +import com.squareup.moshi.*
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/bb3c5d5c7f4c72fc79af6b94023915f9d281e6df/android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/RouteAdapterFactory.kt#L26"></span>com.squareup.moshi.* is a wildcard import. Replace it with fully qualified imports.</td>
    </tr>
  </tbody>
</table>

2020-09-10 22:15 UTC, jenifersantoszup commented on android/sample/src/main/java/br/com/zup/beagle/sample/fragment/TabViewFragment.kt
> +                                        )
This problem has already been corrected in another PR.

2020-09-11 13:27 UTC, tuliopereirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/RouteAdapterFactory.kt
> +        val type: Type = Types.newParameterizedType(Bind::class.java, String::class.java)
What do you think to pass this adapter in the constructor of this class instead of recovering it every time a JSON is deserialised?

2020-09-11 14:28 UTC, uziasferreirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/utils/BeagleConstants.kt
>  }
in this case, these variables is not shared with others, you can create on top of the file the constant, look the example in this PR: https://github.com/ZupIT/beagle/pull/895/files or in-class `ScreenRequestMapperTest` you can see how to declare the `const val` in the top of file.

2020-09-15 17:41 UTC, paulomeurerzup approved these changes

2020-09-15 17:45 UTC, uziasferreirazup submitted a review, later dismissed

2020-09-16 12:41 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-09-16 12:42 UTC, paulomeurerzup requested changes

2020-09-16 12:42 UTC, paulomeurerzup commented on android/beagle/src/main/java/br/com/zup/beagle/android/data/PreFetchHelper.kt
> +            }
We should create tests for this case.

2020-09-16 12:42 UTC, paulomeurerzup commented on android/beagle/src/main/java/br/com/zup/beagle/android/logger/BeagleMessageLogs.kt
> +    }
We should create tests to ensure that this log is been presented.

2020-09-17 13:44 UTC, paulomeurerzup submitted a review, later dismissed

2020-09-17 16:42 UTC, uziasferreirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/action/Navigate.kt
> +            valueOf(url),
```suggestion
            expressionOrValueOf(url),
```

2020-09-18 14:10 UTC, tuliopereirazup approved these changes

2020-09-18 14:23 UTC, uziasferreirazup approved these changes

2020-09-18 14:23 UTC, merged