feat: conditional action android
ZupIT/beagle pull request #898
Opened 2020-09-10 18:28 UTC by luisoliveirazup

### Related Issues
Closes #897 

### Description and Example
Implements the conditional action.
Implement the conditional action according to the second solution suggested in the following issue: #586.

### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2020-09-10 18:29 UTC, botbeaglezup commented on android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/ActionJsonAdapterFactory.kt
> +import br.com.zup.beagle.android.action.*
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/42bad0470261c1d866ea62533f332c540c359024/android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/ActionJsonAdapterFactory.kt#L19"></span>br.com.zup.beagle.android.action.* is a wildcard import. Replace it with fully qualified imports.</td>
    </tr>
  </tbody>
</table>

2020-09-10 18:29 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: <a href="https://github.com/Zu...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/42bad0470261c1d866ea62533f332c540c359024/android/sample/src/main/java/br/com/zup/beagle/sample/fragment/TabViewFragment.kt#L49">android/sample/src/main/java/br/com/zup/beagle/sample/fragment/TabViewFragment.kt#L49</a> - The function onCreateView is too long (78). The maximum length is 60.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_android">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-09-10 18:43 UTC, luisoliveirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/data/serializer/adapter/ActionJsonAdapterFactory.kt
> +import br.com.zup.beagle.android.action.*
change done!

2020-09-10 18:43 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-09-10 18:51 UTC, matheusribeirozup commented on android/beagle/src/main/java/br/com/zup/beagle/android/action/Condition.kt
> +        condition = valueOf(condition),
As described in [this issue](https://github.com/ZupIT/beagle/issues/852), what do you think of doing a validation in case the user inserts an expression in string format locally?

2020-09-10 18:54 UTC, matheusribeirozup requested changes

2020-09-10 18:54 UTC, matheusribeirozup commented on android/beagle/src/main/java/br/com/zup/beagle/android/action/Condition.kt
> +) : Action {
Given that you added a new action, it is necessary to make a test case to cover its deserialization.

2020-09-10 20:12 UTC, luisoliveirazup commented on android/beagle/src/main/java/br/com/zup/beagle/android/action/Condition.kt
> +) : Action {
test created!

2020-09-11 12:32 UTC, tuliopereirazup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/action/Condition.kt
> + * @param condition sets the condition to be resolved.
What do you think to change to `condition should represents a boolean`?

2020-09-11 12:44 UTC, luisoliveirazup commented on backend/widgets/src/main/kotlin/br/com/zup/beagle/widget/action/Condition.kt
> + * @param condition sets the condition to be resolved.
change done!

2020-09-11 12:47 UTC, matheusribeirozup submitted a review, later dismissed

2020-09-11 12:49 UTC, matheusribeirozup commented on android/beagle/src/test/java/br/com/zup/beagle/android/action/ConditionTest.kt
> +        val onTrue: Action = mockk(relaxed = true)
Instead of creating these two variables for each test, what do you think of putting them as an attribute of the class?

2020-09-11 12:57 UTC, luisoliveirazup commented on android/beagle/src/test/java/br/com/zup/beagle/android/action/ConditionTest.kt
> +        val onTrue: Action = mockk(relaxed = true)
change done!

2020-09-11 14:39 UTC, uziasferreirazup approved these changes

2020-09-15 18:38 UTC, matheusribeirozup approved these changes

2020-09-15 20:19 UTC, merged