feat: create the cucumber tests
ZupIT/beagle pull request #908
Opened 2020-09-14 17:49 UTC by viniciusguardieirozup

### Related Issues

### Description and Example

Create a scenario using cucumber

### Checklist

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2020-09-14 18:03 UTC, botbeaglezup commented
<!--
  0 Errors
  2 Warnings: <a href="https://github.com/Zu...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/6d7444ce71bbfe63f95a41a1fb914d09e63f8720/android/sample/src/main/AndroidManifest.xml#L23">android/sample/src/main/AndroidManifest.xml#L23</a> - On SDK version 23 and up, your app data will be automatically backed up and restored on app install. Consider adding the attribute <code>android:fullBackupContent</code> to specify an <code>@xml</code> resource which configures which files to backup. More info: https://developer.android.com/training/backup/autosyncapi.html</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/6d7444ce71bbfe63f95a41a1fb914d09e63f8720/android/sample/src/main/AndroidManifest.xml#L31">android/sample/src/main/AndroidManifest.xml#L31</a> - Attribute <code>usesCleartextTraffic</code> is only used in API level 23 and higher (current min is 19)</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_android">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-09-24 13:38 UTC, botbeaglezup commented on android/sample/src/main/AndroidManifest.xml
>      <application
<table data-meta="generated_by_android">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/084740bc7ab792a3b52f1ddb24e3287aba5a1757/android/sample/src/main/AndroidManifest.xml#L25"></span>On SDK version 23 and up, your app data will be automatically backed up and restored on app install. Consider adding the attribute <code>android:fullBackupContent</code> to specify an <code>@xml</code> resource which configures which files to backup. More info: https://developer.android.com/training/backup/autosyncapi.html</td>
    </tr>
  </tbody>
</table>

2020-10-07 12:27 UTC, diogooliveira-zup requested changes

2020-10-07 12:27 UTC, diogooliveira-zup commented on android/buildSrc/src/main/kotlin/br/com/zup/beagle/Dependencies.kt
> +
Hi! Please remove the unecessary break line

2020-10-07 12:27 UTC, diogooliveira-zup commented on android/sample/build.gradle
> +    }
Same here
```suggestion
        }
        
        buildConfigField "String", "TEST_TAGS", "\"${getTestTags()}\""
    }
```

2020-10-07 12:27 UTC, diogooliveira-zup commented on android/sample/build.gradle
> +screenshots {
same here 
```suggestion
}

screenshots {
```

2020-10-07 12:27 UTC, diogooliveira-zup commented on android/sample/src/androidTest/java/br/com/zup/beagle/sample/cucumber/robots/ScreenRobot.kt
> +    }
same here
```suggestion

        return this
    }
```

2020-10-07 12:27 UTC, diogooliveira-zup commented on android/sample/src/androidTest/java/br/com/zup/beagle/sample/utils/TestUtils.kt
> +}
same here
```suggestion
    }
}
```

2020-10-07 12:27 UTC, diogooliveira-zup commented on android/sample/src/main/java/br/com/zup/beagle/sample/activities/CucumberActivity.kt
> +    fun bffUrl() = intent.extras?.getString(BFF_URL_KEY) ?: "http://10.0.2.2:8080/button"
same here
```suggestion
    }

    fun bffUrl() = intent.extras?.getString(BFF_URL_KEY) ?: "http://10.0.2.2:8080/button"
```

2020-10-20 12:25 UTC, viniciusguardieirozup commented
This tests was added on 1.3.0-support

2020-10-20 12:25 UTC, closed without merging