fix: dynamic object default string conversion
ZupIT/beagle pull request #909
Opened 2020-09-14 22:08 UTC by victorrabelozup

### Related Issues

#878 

### Description and Example

### Checklist

Please, check if these important points are met using `[x]`:

- [ ] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [ ] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [ ] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2020-09-14 22:09 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: PR is classed as Work in Progr...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-09-17 22:50 UTC, botbeaglezup commented on iOS/DynamicObjectExtension.swift
> +
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/b8c6229a91096e881e6239ceb753f99fe5bebfb2/iOS/DynamicObjectExtension.swift#L59"></span>Files should have a single trailing newline.<br />
<code>trailing_newline</code> <code>DynamicObjectExtension.swift:59</code></td>
    </tr>
  </tbody>
</table>

2020-09-20 21:35 UTC, botbeaglezup commented on iOS/DynamicObjectExtension.swift
> +
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/df27d9a9e46ee16aa88d119763dd74ae8cfe9a5d/iOS/DynamicObjectExtension.swift#L68"></span>Limit vertical whitespace to a single empty line. Currently 2.<br />
<code>vertical_whitespace</code> <code>DynamicObjectExtension.swift:68</code></td>
    </tr>
  </tbody>
</table>

2020-09-20 21:35 UTC, botbeaglezup commented on iOS/DynamicObjectExtension.swift
> +
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/df27d9a9e46ee16aa88d119763dd74ae8cfe9a5d/iOS/DynamicObjectExtension.swift#L72"></span>Files should have a single trailing newline.<br />
<code>trailing_newline</code> <code>DynamicObjectExtension.swift:72</code></td>
    </tr>
  </tbody>
</table>

2020-09-21 17:06 UTC, lucasfonsecazup reviewed
Nice job 👍

2020-09-21 17:06 UTC, lucasfonsecazup commented on iOS/DynamicObjectExtension.swift
> +        func arrayDescription(_ array: [(String, DynamicObject)]) -> String {
This function does the same thing as the above function, wouldn't it be nice to encapsulate it in a separate function?

2020-09-21 17:06 UTC, lucasfonsecazup commented on iOS/Schema/Sources/ContextExpression/DynamicObject.swift
> +    private func toString() -> String {
Could not making this method private cause a breakchange for those who use it?

2020-09-22 14:30 UTC, victorrabelozup commented on iOS/Schema/Sources/ContextExpression/DynamicObject.swift
> +    private func toString() -> String {
this is intentional, to force the use of the description property.

2020-09-22 14:32 UTC, victorrabelozup commented on iOS/DynamicObjectExtension.swift
> +extension DynamicObject: AnySnapshotStringConvertible {
This file is imported in both targets(Beagle, Schema) so i putted it in a common path.

2020-09-22 14:33 UTC, victorrabelozup commented on iOS/DynamicObjectExtension.swift
> +        func arrayDescription(_ array: [(String, DynamicObject)]) -> String {
It actually don't make exactly the same thing, but is almost really. And it is already encapsulated inside another function to control the scope.

2020-09-22 18:13 UTC, lucasfonsecazup commented on iOS/DynamicObjectExtension.swift
> +extension DynamicObject: AnySnapshotStringConvertible {
👍

2020-09-22 18:15 UTC, lucasfonsecazup commented on iOS/DynamicObjectExtension.swift
> +        func arrayDescription(_ array: [(String, DynamicObject)]) -> String {
I get it 👍

2020-09-22 18:15 UTC, lucasfonsecazup commented on iOS/Schema/Sources/ContextExpression/DynamicObject.swift
> +    private func toString() -> String {
Ok 👍

2020-09-22 18:16 UTC, lucasfonsecazup submitted a review, later dismissed

2020-09-22 18:50 UTC, caioortu commented on iOS/DynamicObjectExtension.swift
> +        return "[\(description)]"
Here we could use something simpler, a high order function like `map` and `joined`

```suggestion
        let description = array.map { $0.customDescription }.joined(separator: ", ")
        
        return "[\(description)]"
```

2020-09-22 18:50 UTC, caioortu commented on iOS/DynamicObjectExtension.swift
> +        return arrayDescription(array)
Similarly to the `arrayDescription` function, we could also make simpler and more efficient with high order functions

```suggestion
        let array = dictionary.map({ ($0, $1) }).sorted { $0.0 < $1.0 }
        
        func arrayDescription(_ array: [(String, DynamicObject)]) -> String {
            let description = array.map { "\($0.0): \($0.1.customDescription)" }.joined(separator: ", ")
            
            return "[\(description)]"
        }
        
        return arrayDescription(array)
```

2020-09-22 19:04 UTC, caioortu commented on iOS/DynamicObjectExtension.swift
> +extension DynamicObject: AnySnapshotStringConvertible {
Since `DynamicObject` is defined inside Schema we could have its extension also inside Schema and then just create a reference to it inside Beagle. This way we still have just one file and we don't have to have this one swift file in the root of the workspace.

2020-09-22 21:29 UTC, victorrabelozup commented on iOS/DynamicObjectExtension.swift
> +extension DynamicObject: AnySnapshotStringConvertible {
This extension is in the test targets, it can't be imported.

2020-09-23 14:37 UTC, caioortu submitted a review, later dismissed

2020-09-23 16:57 UTC, victorrabelozup commented on iOS/Schema/Sources/ContextExpression/DynamicObject.swift
> +    private func toString() -> String {
It really is a "by the book" strategy and is not wrong, but in my opinion this case is a little better with this approach. We can discuss if you want. :)

2020-09-23 18:16 UTC, lucasaraujo approved these changes

2020-09-24 03:40 UTC, theffc requested changes
CI is not passing

2020-09-24 14:51 UTC, theffc commented
I've just investigated the problem, it's happening in the lane `check_if_beagle_works_via_cocoapods_integration`, that will try to use beagle in an example project via cocoa pods. When this error occurs, it's probably due to some file that was added or removed from the project, but cocoa pods is not being able to get that from the file pattern it uses.
In this example it was because of the file `DynamicObjectExtension.swift` which should belong to the target `BeagleSchemaTests`, but it's not inside a `Tests` folder, and does not contain `Test` in its name. That way, cocoa pods is mistakenly adding it to `BeagleSchema` target

2020-09-25 11:48 UTC, lucasfonsecazup reviewed
:)

2020-09-25 11:48 UTC, lucasfonsecazup commented on iOS/Sources/Beagle/Sources/Common/Extensions/Tests/DynamicObjectExtension.swift
> +extension DynamicObject: AnySnapshotStringConvertible {
[Doubt]
Do we really have to duplicate this class in `schema` and  `core` ? Is there no way to reuse this extension?

2020-09-25 18:08 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-09-25 18:18 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: <a href="https://github.com/Zu...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/fd358af9f5ae06cd28275d4e6fc78e68be7a4552/iOS/Sources/Beagle/Sources/Networking/Repository.swift#L172">iOS/Sources/Beagle/Sources/Networking/Repository.swift#L172</a> - TODOs should be resolved (change loadFromTextError insid…).<br />
<code>todo</code> <code>Repository.swift:172</code></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_ios">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-09-25 18:57 UTC, victorrabelozup commented on iOS/Sources/Beagle/Sources/Common/Extensions/Tests/DynamicObjectExtension.swift
> +extension DynamicObject: AnySnapshotStringConvertible {
We need the extension in both targets. And I really don't want to create 2 files, just made an alteration to use the same file.

2020-09-25 19:03 UTC, theffc approved these changes

2020-09-25 20:41 UTC, caioortu approved these changes

2020-09-28 13:41 UTC, merged