feature: image expression
ZupIT/beagle pull request #914
Opened 2020-09-15 18:10 UTC by luisgustavozup

Closes #913 

### Description and Example

- Changed url and mobileId to expression type.
- ImagePath is no longer expression

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

2020-09-15 18:11 UTC, botbeaglezup commented
<!--
  1 Error: The title of PR not follow the...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-09-15 18:18 UTC, gabrielmarsonzup approved these changes

2020-09-15 18:20 UTC, caioortu submitted a review, later dismissed

2020-09-18 13:24 UTC, botbeaglezup commented on iOS/Example/BeagleDemo/BeagleDemo/Screens/ListViewScreen.swift
>          }
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/81735f3aab3cde7851b4b6fec0e375a8ee2803d0/iOS/Example/BeagleDemo/BeagleDemo/Screens/ListViewScreen.swift#L40"></span>Closure end should have the same indentation as the line that started it. Expected 9, got 8.<br />
<code>closure_end_indentation</code> <code>ListViewScreen.swift:40</code></td>
    </tr>
  </tbody>
</table>

2020-09-21 13:09 UTC, heliojuniorzup approved these changes

2020-09-22 15:59 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-09-22 16:11 UTC, botbeaglezup commented on iOS/Example/BeagleDemo/BeagleDemo/Screens/ListViewScreen.swift
> +                navigationBarItems: [NavigationBarItem(
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/a69b4d143bad497c9056bc65e97f960c6a111e6c/iOS/Example/BeagleDemo/BeagleDemo/Screens/ListViewScreen.swift#L34"></span>Multiline literals should have their surrounding brackets in a new line.<br />
<code>multiline_literal_brackets</code> <code>ListViewScreen.swift:34</code></td>
    </tr>
  </tbody>
</table>

2020-09-22 16:11 UTC, botbeaglezup commented on iOS/Example/BeagleDemo/BeagleDemo/Screens/ListViewScreen.swift
> +                    action: SetContext(contextId: "img", value: "imageBeagle"))]
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/a69b4d143bad497c9056bc65e97f960c6a111e6c/iOS/Example/BeagleDemo/BeagleDemo/Screens/ListViewScreen.swift#L37"></span>Multiline literals should have their surrounding brackets in a new line.<br />
<code>multiline_literal_brackets</code> <code>ListViewScreen.swift:37</code></td>
    </tr>
  </tbody>
</table>

2020-09-22 16:11 UTC, botbeaglezup commented on iOS/Example/BeagleDemo/BeagleDemo/Screens/ListViewScreen.swift
>          }
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/a69b4d143bad497c9056bc65e97f960c6a111e6c/iOS/Example/BeagleDemo/BeagleDemo/Screens/ListViewScreen.swift#L47"></span>Closure end should have the same indentation as the line that started it. Expected 9, got 8.<br />
<code>closure_end_indentation</code> <code>ListViewScreen.swift:47</code></td>
    </tr>
  </tbody>
</table>

2020-09-23 13:47 UTC, caioortu commented on iOS/Schema/Sources/Action/Types/Navigate/Navigate.swift
> -        public init(url: String, shouldPrefetch: Bool = false, fallback: Screen? = nil) {
Was this deprecated warning supposed to be removed?

2020-09-23 13:54 UTC, gabcoelho commented on iOS/Schema/Sources/Action/Types/Navigate/Navigate.swift
> -        public init(url: String, shouldPrefetch: Bool = false, fallback: Screen? = nil) {
Yes, we created a new constructor to accept both cases and avoid warnings when we use something like `"@{url}"` ExpressibleString is a typealias for String, so that our users can understand that he can use String and Expression<String> as well

`        public init(url: ExpressibleString, shouldPrefetch: Bool = false, fallback: Screen? = nil) 
`

2020-09-23 14:10 UTC, caioortu approved these changes

2020-09-24 03:14 UTC, theffc requested changes

2020-09-24 03:14 UTC, theffc commented on iOS/Sources/Beagle/Sources/Components/Layout+Renderable/Screen/Tests/ScreenComponentTests.swift
> +    }
I think that if we only test the first time of `observe` being called, we should already know that it works. This change will allow us reduce weird code, and we can leave the check for multiple `observe` iteration to more specific `observe` tests

```suggestion
    func testNavigationBarItemWithContextOnImage() {
        // Given
        let dependencies = BeagleDependencies()
        dependencies.appBundle = Bundle(for: ScreenComponentTests.self)
        
        let barItem = NavigationBarItem(image: "@{image}", text: "", action: ActionDummy())

        let screen = Screen(
            safeArea: SafeArea.all,
            navigationBar: .init(title: "title", showBackButton: true, navigationBarItems: [barItem]),
            child: Text("test"),
            context: Context(id: "image", value: "shuttle")
        )

        let controller = BeagleScreenViewController(viewModel: .init(
            screenType: .declarative(screen),
            dependencies: dependencies
        ))
        
        // Then
        assertSnapshotImage(controller, size: .custom(CGSize(width: 150, height: 80)))
    }
```

2020-09-24 11:33 UTC, gabcoelho commented on iOS/Schema/Sources/ContextExpression/Expression.swift
> +public typealias ExpressibleString = String
I still prefer ExpressibleString haha but I can understand how it could become kinda of confusing for our users. And `StringOrExpression` would be much clearer so maybe they wouldn't even need to search for an explanation on what it is actually

2020-09-24 11:41 UTC, gabcoelho commented on iOS/Sources/Beagle/Sources/Components/Layout+Renderable/Screen/Tests/ScreenComponentTests.swift
> +    }
nice, that is much better!

2020-09-24 14:32 UTC, lucasfonsecazup submitted a review, later dismissed
Nice job 👍

2020-09-24 14:32 UTC, lucasfonsecazup commented on iOS/Example/BeagleDemo/BeagleDemo/Screens/ImageScreen.swift
> +    init(path: String, data: [String: String]?) {
[Doubt]
Why is there an empty init?

2020-09-24 14:32 UTC, lucasfonsecazup commented on iOS/Sources/Beagle/Sources/Components/Image+Renderable/Image+Renderable.swift
> +                    self.setImageFromAsset(named: mobileId, bundle: renderer.controller.dependencies.appBundle, imageView: image)
Can you guarantee that this `self` reference will not cause a retain cycle? If not, use `weak self`.

2020-09-24 14:32 UTC, lucasfonsecazup commented on iOS/Sources/Beagle/Sources/Components/Image+Renderable/Image+Renderable.swift
> +                    token = self.setRemoteImage(from: url, placeholder: remote.placeholder, imageView: image, renderer: renderer)
Can you guarantee that this `self` reference will not cause a retain cycle? If not, use `weak self`.

2020-09-24 14:37 UTC, gabcoelho commented on iOS/Example/BeagleDemo/BeagleDemo/Screens/ImageScreen.swift
> +    init(path: String, data: [String: String]?) {
this is actually because of the `DeeplinkScreen` protocol, I will add a comment to it 😁

2020-09-24 14:43 UTC, gabcoelho commented on iOS/Sources/Beagle/Sources/Components/Image+Renderable/Image+Renderable.swift
> +                    self.setImageFromAsset(named: mobileId, bundle: renderer.controller.dependencies.appBundle, imageView: image)
`self` here actually applies to the `struct Image`, so I don't see it causing a retain cycle

2020-09-24 15:42 UTC, botbeaglezup commented on iOS/Sources/Beagle/Sources/Components/Layout+Renderable/Screen/NavigationBar+UIKit.swift
> +            /// Since `BeagleScreenViewController` creates a different view hierarchy, to get the correct hierarchy we need to use the `view` from our `controller`.
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/fb15f16ead7272469f2284e6f8fa207297b83d29/iOS/Sources/Beagle/Sources/Components/Layout+Renderable/Screen/NavigationBar+UIKit.swift#L58"></span>A doc comment should be attached to a declaration.<br />
<code>orphaned_doc_comment</code> <code>NavigationBar+UIKit.swift:58</code></td>
    </tr>
  </tbody>
</table>

2020-09-24 17:16 UTC, lucasfonsecazup approved these changes

2020-09-25 17:47 UTC, theffc approved these changes

2020-09-25 21:43 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: <a href="https://github.com/Zu...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/2cae87bb3af0320821d3a3bf2c21be2d9eaf3541/iOS/Sources/Beagle/Sources/Renderer/BeagleScreenViewController.swift#L53">iOS/Sources/Beagle/Sources/Renderer/BeagleScreenViewController.swift#L53</a> - TODOs should be resolved (This workaround should be remo…).<br />
<code>todo</code> <code>BeagleScreenViewController.swift:53</code></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_ios">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-10-05 12:08 UTC, lucasaraujo commented on iOS/Sources/Beagle/Sources/Renderer/BeagleScreenViewController.swift
> +    }
I didn't understand why it is needed.

2020-10-05 12:19 UTC, gabcoelho commented on iOS/Sources/Beagle/Sources/Renderer/BeagleScreenViewController.swift
> +    }
this was being used to trigger `applyLayout` from `viewDidLayoutSubviews` when we rotated the device. But I just checked and it works without it, so it is no longer necessary and I will be deleted 😊

2020-10-06 14:14 UTC, victorrabelozup commented on iOS/Sources/Beagle/Sources/Components/TabBar+Renderable/TabBarUIComponent.swift
> +            if superview != nil, shouldCreateTabItemsView {
if let is more performatic to nil comparison.

```suggestion
            if let _ = superview, shouldCreateTabItemsView {
```

2020-10-06 19:03 UTC, botbeaglezup commented on iOS/Sources/Beagle/Sources/Components/TabBar+Renderable/TabBarUIComponent.swift
> +                // TODO: setNeedLayout should call layoutIfNeeded
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/39896cdaa0f9e659a101335a874192cc99dd36a4/iOS/Sources/Beagle/Sources/Components/TabBar+Renderable/TabBarUIComponent.swift#L242"></span>TODOs should be resolved (setNeedLayout should call layo…).<br />
<code>todo</code> <code>TabBarUIComponent.swift:242</code></td>
    </tr>
  </tbody>
</table>

2020-10-06 19:03 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: <a href="https://github.com/Zu...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/ZupIT/beagle/blob/39896cdaa0f9e659a101335a874192cc99dd36a4/iOS/Sources/Beagle/Sources/Renderer/BeagleScreenViewController.swift#L53">iOS/Sources/Beagle/Sources/Renderer/BeagleScreenViewController.swift#L53</a> - TODOs should be resolved (This workaround should be remo…).<br />
<code>todo</code> <code>BeagleScreenViewController.swift:53</code></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_ios">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-10-07 13:03 UTC, victorrabelozup approved these changes

2020-10-09 17:42 UTC, lucasaraujo approved these changes

2020-10-09 20:18 UTC, botbeaglezup commented on iOS/Sources/Beagle/Sources/Components/TabBar+Renderable/TabBarUIComponent.swift
> +                // TODO: setNeedLayout should call layoutIfNeeded
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/4ef64bf53cf433f5a3c5a4cd0756a5c1a52351f1/iOS/Sources/Beagle/Sources/Components/TabBar+Renderable/TabBarUIComponent.swift#L244"></span>TODOs should be resolved (setNeedLayout should call layo…).<br />
<code>todo</code> <code>TabBarUIComponent.swift:244</code></td>
    </tr>
  </tbody>
</table>

2020-10-09 20:43 UTC, botbeaglezup commented on iOS/Sources/Beagle/Sources/Components/TabBar+Renderable/TabBarUIComponent.swift
> +                // TODO: setNeedLayout should call layoutIfNeeded
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/160010787fcf2ec363ba0dcb8ef5e3954c30ec1c/iOS/Sources/Beagle/Sources/Components/TabBar+Renderable/TabBarUIComponent.swift#L241"></span>TODOs should be resolved (setNeedLayout should call layo…).<br />
<code>todo</code> <code>TabBarUIComponent.swift:241</code></td>
    </tr>
  </tbody>
</table>

2020-10-13 13:31 UTC, dantes-git approved these changes

2020-10-13 14:08 UTC, merged