fix: textInput onBlur
ZupIT/beagle pull request #944
Opened 2020-09-24 19:02 UTC by caioortu

### Related Issues

Closes #900 

### Checklist

Please, check if these important points are met using `[x]`:

- [ ] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [ ] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [ ] I am willing to follow-up on review comments in a timely manner.

2020-09-24 20:56 UTC, theffc commented
@yandiaszup do you think this solution would work for you?

2020-09-25 11:36 UTC, lucasfonsecazup submitted a review, later dismissed

2020-09-25 12:37 UTC, dantes-git requested changes

2020-09-25 12:37 UTC, dantes-git commented on iOS/Sources/Beagle/Sources/Components/TextInput+Renderable/TextInput.swift
> +            return true
Here we cannot return true because if a textinput is using binding, it will be updated twice. Example:

```swift 
TextInput(
    value: "@{context1}",
    onChange: [
        SetContext(
            contextId: "context1",
            value: "@{onChange.value}"
        )
    ]
)
```
We need to creat a test for this.

2020-09-28 13:58 UTC, dantes-git approved these changes

2020-09-28 17:34 UTC, yandiaszup approved these changes

2020-09-28 20:12 UTC, merged