fix: Global Context
ZupIT/beagle pull request #945
Opened 2020-09-25 12:12 UTC by heliojuniorzup

### Related Issues

Closes #928 

### Checklist

Please, check if these important points are met using `[x]`:

- [ x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [ x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x ] I am willing to follow-up on review comments in a timely manner.

2020-09-25 12:24 UTC, botbeaglezup commented on iOS/Sources/Beagle/Sources/ContextExpression/Tests/GlobalContextTests.swift
> +    private lazy var globalContextWithDictionary = Context(id: globalId, value: .dictionary([globalId : "Dictionary value"]))
<table data-meta="generated_by_ios">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/ZupIT/beagle/blob/b7a52e1adef9003bc1e0600c761403765bfdef66/iOS/Sources/Beagle/Sources/ContextExpression/Tests/GlobalContextTests.swift#L33"></span>Colons should be next to the identifier when specifying a type and next to the key in dictionary literals.<br />
<code>colon</code> <code>GlobalContextTests.swift:33</code></td>
    </tr>
  </tbody>
</table>

2020-09-25 14:01 UTC, caioortu submitted a review, later dismissed

2020-09-28 16:35 UTC, yandiaszup requested changes

2020-09-28 16:35 UTC, yandiaszup commented on iOS/Sources/Beagle/Sources/ContextExpression/GlobalContext.swift
> +    }
There is a comment here and this function its aways returning nil

2020-09-30 12:13 UTC, lucasfonsecazup reviewed
The solution is very good, however there are some points.

2020-09-30 12:13 UTC, lucasfonsecazup commented on iOS/Sources/Beagle/Sources/ContextExpression/Tests/GlobalContextTests.swift
>      func testGetContext() {
We are adopting the comments `// Given // When // Then` as convention -> https://github.com/ZupIT/beagle/wiki/Swift-Style-Guide#tests

2020-09-30 20:31 UTC, botbeaglezup commented
<!--
  0 Errors
  1 Warning: PR is classed as Work in Progr...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-10-01 13:50 UTC, caioortu approved these changes

2020-10-01 16:36 UTC, yandiaszup approved these changes

2020-10-05 13:19 UTC, gabcoelho approved these changes

2020-10-05 17:00 UTC, lucasaraujo approved these changes

2020-10-05 17:26 UTC, merged