refactor: add children action
ZupIT/beagle pull request #959
Opened 2020-09-28 20:57 UTC by luisoliveirazup

### Related Issues
closes #956 

### Description and Example
On the IOS and web platforms they are following the contract under the name AddChildren, but on the Android and Backend platforms they are under the name AddChildrenAction

expected: Result that all platforms follow the contract defined as AddChildren

### Checklist

Please, check if these important points are met using `[x]`:

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

[PR Guide]: https://github.com/ZupIT/beagle/blob/master/doc/contributing/pull_requests.md

2020-09-28 21:02 UTC, uziasferreirazup requested changes

2020-09-28 21:02 UTC, uziasferreirazup commented on android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt
> +    fun `make should return moshi to deserialize a AddChildren` (){
please follow the new pattern name:
example: ``GIVEN response data is an integer WHEN toResponse is called THEN it should return an Int object``()

2020-09-28 21:02 UTC, uziasferreirazup commented on android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt
> +    fun `make should return moshi to deserialize a AddChildren` (){
add the test to serialization and deserialization, you can look at the tests to know how to do:
 fun `make should return moshi to deserialize a Container`
 fun `make should return moshi to serialize a Container`

2020-09-29 01:15 UTC, luisoliveirazup commented on android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt
> +    fun `make should return moshi to deserialize a AddChildren` (){
change done!

2020-09-29 01:16 UTC, luisoliveirazup commented on android/beagle/src/test/java/br/com/zup/beagle/android/data/serializer/BeagleMoshiTest.kt
> +    fun `make should return moshi to deserialize a AddChildren` (){
change done!

2020-09-29 10:30 UTC, uziasferreirazup approved these changes

2020-09-29 12:36 UTC, viniciusguardieirozup approved these changes

2020-09-29 12:40 UTC, merged