Fix/container
ZupIT/beagle pull request #982
Opened 2020-10-02 17:37 UTC by viniciusguardieirozup

### Related Issues

#973 

### Description and Example

Crash app when startActivity is called using a JSON without a ScreenComponent, this happen because in the method onResume on BeagleActivity, before call the fetch was doing a cast to ScreenComponent 

### Checklist

- [x] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [x] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [x] I am willing to follow-up on review comments in a timely manner.

2020-10-02 17:37 UTC, botbeaglezup commented
<!--
  1 Error: The title of PR not follow the...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-10-05 19:28 UTC, diogooliveira-zup requested changes

2020-10-05 19:28 UTC, diogooliveira-zup commented on android/beagle/src/test/java/br/com/zup/beagle/android/view/viewmodel/BeagleViewModelTest.kt
> +    fun `fetch should return render ViewState`() {
Hi! Please add GIVEN WHEN THEN pattern to the test

2020-10-05 19:28 UTC, diogooliveira-zup commented on android/beagle/src/test/java/br/com/zup/beagle/android/view/viewmodel/BeagleViewModelTest.kt
> +    fun `fetch should return a error ViewState`() {
The same above

2020-10-05 19:28 UTC, diogooliveira-zup commented on android/beagle/src/test/java/br/com/zup/beagle/android/view/viewmodel/BeagleViewModelTest.kt
> +    fun `fetch should return a error ViewState retry`() {
The same above

2020-10-06 12:45 UTC, diogooliveira-zup approved these changes

2020-10-06 13:06 UTC, uziasferreirazup approved these changes

2020-10-06 13:07 UTC, merged